//
//  EuropeanSquads2020.swift
//  Retro Season Manager
//
//  Hand-authored 2020/21-era rosters for the same 8 foreign giant club
//  names used by EuropeanSquads2000.swift and EuropeanSquads2010.swift —
//  aged forward from the 2010 sheet using the same technique as
//  HistoricalSquads2020.swift: anyone 30 or younger in 2010 carries their
//  fictional name into this decade (aged up, rating adjusted for a
//  plausible ten-year arc), everyone older has retired and is replaced by
//  a fresh fictional name breaking into the side.
//

import Foundation

enum EuropeanSquads2020 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Bernabéu Whites": [
            HistoricalPlayer(name: "Iker Salaberri", detailedPosition: .goalkeeper, age: 39, rating: 85),
            HistoricalPlayer(name: "Antonio Novak", detailedPosition: .goalkeeper, age: 33, rating: 70),
            HistoricalPlayer(name: "Sergio Bernal", detailedPosition: .centreBack, age: 34, rating: 86, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Pepe Alvarenga", detailedPosition: .centreBack, age: 37, rating: 81),
            HistoricalPlayer(name: "Achraf Benali", detailedPosition: .centreBack, age: 20, rating: 80),
            HistoricalPlayer(name: "Marcelo Nascimento", detailedPosition: .leftBack, age: 32, rating: 87),
            HistoricalPlayer(name: "Alvaro Cerezo", detailedPosition: .rightBack, age: 37, rating: 71),
            HistoricalPlayer(name: "Xabi Bernal", detailedPosition: .holding, age: 38, rating: 83),
            HistoricalPlayer(name: "Sami Reinholt", detailedPosition: .holding, age: 33, rating: 86, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mesut Aydin", detailedPosition: .attackingMid, age: 31, rating: 90, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Angel Di Bello", detailedPosition: .rightWing, age: 32, rating: 88, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Cristiano Renaldo", detailedPosition: .leftWing, age: 35, rating: 93, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Gonzalo Tamudo", detailedPosition: .striker, age: 32, rating: 91),
            HistoricalPlayer(name: "Karim Idrissi", detailedPosition: .striker, age: 32, rating: 88),
            HistoricalPlayer(name: "Kaká Ribeiro", detailedPosition: .attackingMid, age: 38, rating: 77, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Lassana Diallo", detailedPosition: .holding, age: 35, rating: 74),
            HistoricalPlayer(name: "Raul Bernal", detailedPosition: .centreBack, age: 34, rating: 74),
            HistoricalPlayer(name: "Esteban Cerezo", detailedPosition: .attackingMid, age: 33, rating: 78),
        ],
        "Camp Blaugrana": [
            HistoricalPlayer(name: "Victor Salaberri", detailedPosition: .goalkeeper, age: 38, rating: 82),
            HistoricalPlayer(name: "Marc Oyono", detailedPosition: .goalkeeper, age: 21, rating: 78),
            HistoricalPlayer(name: "Dani Cerezo", detailedPosition: .rightBack, age: 37, rating: 82),
            HistoricalPlayer(name: "Gerard Bernal", detailedPosition: .centreBack, age: 33, rating: 90),
            HistoricalPlayer(name: "Iñigo Salaberri", detailedPosition: .centreBack, age: 21, rating: 81),
            HistoricalPlayer(name: "Théo Junqueira", detailedPosition: .leftBack, age: 20, rating: 76),
            HistoricalPlayer(name: "Sergio Salgueiro", detailedPosition: .holding, age: 31, rating: 87),
            HistoricalPlayer(name: "Youri Bastos", detailedPosition: .centralMid, age: 20, rating: 80, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Andres Cerezo", detailedPosition: .attackingMid, age: 36, rating: 88, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Lionel Mesi", detailedPosition: .rightWing, age: 33, rating: 95, secondaryPositions: [.striker, .attackingMid]),
            HistoricalPlayer(name: "David Cerezo", detailedPosition: .striker, age: 38, rating: 81, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Pedro Idrissi", detailedPosition: .rightWing, age: 33, rating: 88, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Javier Pellegrino", detailedPosition: .holding, age: 36, rating: 80, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Ibrahim Ndiaye", detailedPosition: .leftWing, age: 34, rating: 74),
            HistoricalPlayer(name: "Nabil Achour", detailedPosition: .centralMid, age: 20, rating: 74),
            HistoricalPlayer(name: "Maxwell Salgueiro", detailedPosition: .leftBack, age: 38, rating: 68),
            HistoricalPlayer(name: "Bojan Novak", detailedPosition: .striker, age: 30, rating: 83),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .centralMid, age: 29, rating: 81),
        ],
        "Bavarian Reds": [
            HistoricalPlayer(name: "Yassin Berger", detailedPosition: .goalkeeper, age: 21, rating: 80),
            HistoricalPlayer(name: "Thomas Kral", detailedPosition: .goalkeeper, age: 34, rating: 64),
            HistoricalPlayer(name: "Philipp Krause", detailedPosition: .rightBack, age: 36, rating: 85, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Niklas Sorensen", detailedPosition: .centreBack, age: 20, rating: 79),
            HistoricalPlayer(name: "Martin Marotta", detailedPosition: .centreBack, age: 39, rating: 71),
            HistoricalPlayer(name: "Holger Fischer", detailedPosition: .centreBack, age: 31, rating: 82, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Bastian Wenzel", detailedPosition: .centralMid, age: 35, rating: 85, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Robin Achterberg", detailedPosition: .holding, age: 21, rating: 78),
            HistoricalPlayer(name: "Arjen Vogel", detailedPosition: .rightWing, age: 36, rating: 88, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Franck Dubois", detailedPosition: .leftWing, age: 37, rating: 86, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Thomas Reuter", detailedPosition: .rightWing, age: 30, rating: 91, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Malick Toure", detailedPosition: .striker, age: 21, rating: 80),
            HistoricalPlayer(name: "Toni Steiner", detailedPosition: .attackingMid, age: 30, rating: 85),
            HistoricalPlayer(name: "Elias Vandersteen", detailedPosition: .holding, age: 20, rating: 75),
            HistoricalPlayer(name: "Luiz Nascimento", detailedPosition: .holding, age: 33, rating: 78),
            HistoricalPlayer(name: "Mateo Kranjc", detailedPosition: .centreBack, age: 20, rating: 74),
            HistoricalPlayer(name: "Diego Girard", detailedPosition: .leftBack, age: 30, rating: 77),
            HistoricalPlayer(name: "David Steiner", detailedPosition: .leftBack, age: 28, rating: 79, secondaryPositions: [.centralMid]),
        ],
        "Turin Bianconeri": [
            HistoricalPlayer(name: "Wojciech Adamski", detailedPosition: .goalkeeper, age: 22, rating: 82),
            HistoricalPlayer(name: "Denis Marchetti", detailedPosition: .goalkeeper, age: 20, rating: 70),
            HistoricalPlayer(name: "Giorgio Amadori", detailedPosition: .centreBack, age: 36, rating: 82, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Leonardo Fiore", detailedPosition: .centreBack, age: 33, rating: 84),
            HistoricalPlayer(name: "Andrea Rinaldi", detailedPosition: .centreBack, age: 39, rating: 72),
            HistoricalPlayer(name: "Rafael Toledo", detailedPosition: .centreBack, age: 21, rating: 78),
            HistoricalPlayer(name: "Sami Aktas", detailedPosition: .rightBack, age: 21, rating: 74),
            HistoricalPlayer(name: "Claudio Fanti", detailedPosition: .centralMid, age: 34, rating: 80, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Milos Ivanov", detailedPosition: .rightWing, age: 35, rating: 77, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Felipe Nascimento", detailedPosition: .holding, age: 37, rating: 69),
            HistoricalPlayer(name: "Duvan Restrepo", detailedPosition: .striker, age: 21, rating: 76),
            HistoricalPlayer(name: "Vincenzo Amadori", detailedPosition: .striker, age: 39, rating: 67),
            HistoricalPlayer(name: "Amauri Salgueiro", detailedPosition: .striker, age: 39, rating: 69),
            HistoricalPlayer(name: "Diego Cerezo", detailedPosition: .attackingMid, age: 35, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Enzo Falchi", detailedPosition: .leftBack, age: 20, rating: 71),
            HistoricalPlayer(name: "Kwame Osafo", detailedPosition: .rightWing, age: 20, rating: 74),
            HistoricalPlayer(name: "Alessio Amadori", detailedPosition: .rightWing, age: 33, rating: 76),
            HistoricalPlayer(name: "Paolo Fanti", detailedPosition: .leftBack, age: 33, rating: 73),
        ],
        "San Siro Rossoneri": [
            HistoricalPlayer(name: "Donnarumma Vitale", detailedPosition: .goalkeeper, age: 21, rating: 82),
            HistoricalPlayer(name: "Marco Novak", detailedPosition: .goalkeeper, age: 39, rating: 61),
            HistoricalPlayer(name: "Theo Bertoli", detailedPosition: .rightBack, age: 20, rating: 76),
            HistoricalPlayer(name: "Matteo Scaglia", detailedPosition: .centreBack, age: 21, rating: 79),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .centreBack, age: 35, rating: 85),
            HistoricalPlayer(name: "Luca Fanti", detailedPosition: .leftBack, age: 38, rating: 65),
            HistoricalPlayer(name: "Sandro Locatelli", detailedPosition: .holding, age: 21, rating: 78),
            HistoricalPlayer(name: "Youssouf Keita", detailedPosition: .holding, age: 20, rating: 75),
            HistoricalPlayer(name: "Nicolo Fagioli", detailedPosition: .centralMid, age: 20, rating: 77),
            HistoricalPlayer(name: "Rafa Leon", detailedPosition: .attackingMid, age: 21, rating: 79),
            HistoricalPlayer(name: "Robinho Farias", detailedPosition: .rightWing, age: 36, rating: 80, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Zlatan Ibsen", detailedPosition: .striker, age: 39, rating: 85),
            HistoricalPlayer(name: "Alexandre Salgueiro", detailedPosition: .striker, age: 31, rating: 86),
            HistoricalPlayer(name: "Kevin-Prince Amara", detailedPosition: .attackingMid, age: 33, rating: 82, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Erik Solberg", detailedPosition: .holding, age: 20, rating: 73),
            HistoricalPlayer(name: "Ignazio Fanti", detailedPosition: .rightBack, age: 34, rating: 69),
            HistoricalPlayer(name: "Divock Mbappe", detailedPosition: .striker, age: 21, rating: 80),
            HistoricalPlayer(name: "Antonio Rinaldi", detailedPosition: .attackingMid, age: 38, rating: 69, secondaryPositions: [.striker]),
        ],
        "San Siro Nerazzurri": [
            HistoricalPlayer(name: "Andre Onwuka", detailedPosition: .goalkeeper, age: 21, rating: 79),
            HistoricalPlayer(name: "Filip Nowak", detailedPosition: .goalkeeper, age: 20, rating: 68),
            HistoricalPlayer(name: "Maicon Nascimento", detailedPosition: .rightBack, age: 38, rating: 82),
            HistoricalPlayer(name: "Denzel Cuypers", detailedPosition: .rightBack, age: 20, rating: 78),
            HistoricalPlayer(name: "Mateo Perisic", detailedPosition: .centreBack, age: 21, rating: 80),
            HistoricalPlayer(name: "Cristian Belkacem", detailedPosition: .leftBack, age: 39, rating: 72, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Kristjan Asani", detailedPosition: .centreBack, age: 20, rating: 77),
            HistoricalPlayer(name: "Youssef Bamba", detailedPosition: .holding, age: 21, rating: 79),
            HistoricalPlayer(name: "Wesley Reuter", detailedPosition: .attackingMid, age: 36, rating: 87, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Marco Vitali", detailedPosition: .holding, age: 20, rating: 76),
            HistoricalPlayer(name: "Goran Kral", detailedPosition: .rightWing, age: 37, rating: 71, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Samuel Ndiaye", detailedPosition: .striker, age: 39, rating: 84, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ivo Radic", detailedPosition: .centralMid, age: 21, rating: 79),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .holding, age: 38, rating: 72),
            HistoricalPlayer(name: "Fredy Idrissi", detailedPosition: .centralMid, age: 34, rating: 74),
            HistoricalPlayer(name: "Jonathan Girard", detailedPosition: .leftWing, age: 32, rating: 77),
            HistoricalPlayer(name: "Lautaro Reyes", detailedPosition: .striker, age: 21, rating: 83),
            HistoricalPlayer(name: "Luc Fanti", detailedPosition: .striker, age: 28, rating: 72),
        ],
        "Amsterdam Godenzonen": [
            HistoricalPlayer(name: "Kenneth Reinholt", detailedPosition: .goalkeeper, age: 37, rating: 69),
            HistoricalPlayer(name: "Maarten Krause", detailedPosition: .goalkeeper, age: 37, rating: 72),
            HistoricalPlayer(name: "Toby Fischer", detailedPosition: .centreBack, age: 31, rating: 80, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Jan Wenzel", detailedPosition: .centreBack, age: 33, rating: 83, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Sven Rasmussen", detailedPosition: .centreBack, age: 20, rating: 74),
            HistoricalPlayer(name: "Gregory Steiner", detailedPosition: .rightBack, age: 32, rating: 82),
            HistoricalPlayer(name: "Urby Vogel", detailedPosition: .leftBack, age: 34, rating: 72, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Demy Novak", detailedPosition: .holding, age: 37, rating: 68),
            HistoricalPlayer(name: "Christian Larsen", detailedPosition: .attackingMid, age: 28, rating: 85, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Luuk Girard", detailedPosition: .striker, age: 30, rating: 81),
            HistoricalPlayer(name: "Miralem Ivanov", detailedPosition: .rightWing, age: 32, rating: 79),
            HistoricalPlayer(name: "Luis Bencosme", detailedPosition: .striker, age: 33, rating: 89, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Rasmus Bergman", detailedPosition: .centralMid, age: 35, rating: 69),
            HistoricalPlayer(name: "Vurnon Idrissi", detailedPosition: .centralMid, age: 31, rating: 76),
            HistoricalPlayer(name: "Marko Krause", detailedPosition: .centralMid, age: 33, rating: 72),
            HistoricalPlayer(name: "Thomas Wenzel", detailedPosition: .centreBack, age: 34, rating: 76),
            HistoricalPlayer(name: "Ismail Fanti", detailedPosition: .attackingMid, age: 31, rating: 72),
            HistoricalPlayer(name: "Jan Fischer", detailedPosition: .rightBack, age: 30, rating: 73),
        ],
        "Dragão Dragons": [
            HistoricalPlayer(name: "Diogo Marchetti", detailedPosition: .goalkeeper, age: 21, rating: 72),
            HistoricalPlayer(name: "Diego Cerezo", detailedPosition: .goalkeeper, age: 34, rating: 61),
            HistoricalPlayer(name: "Alvaro Marotta", detailedPosition: .leftBack, age: 34, rating: 73, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Rolando Nascimento", detailedPosition: .centreBack, age: 34, rating: 75),
            HistoricalPlayer(name: "Nicolas Bernal", detailedPosition: .centreBack, age: 32, rating: 81),
            HistoricalPlayer(name: "Tiago Salgueiro", detailedPosition: .centreBack, age: 20, rating: 70),
            HistoricalPlayer(name: "Cristian Ivanov", detailedPosition: .rightBack, age: 36, rating: 69),
            HistoricalPlayer(name: "Fernando Salgueiro", detailedPosition: .holding, age: 32, rating: 84),
            HistoricalPlayer(name: "Joao Cerezo", detailedPosition: .centralMid, age: 33, rating: 86, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Fredy Marotta", detailedPosition: .centralMid, age: 34, rating: 76),
            HistoricalPlayer(name: "Givanildo Marotta", detailedPosition: .rightWing, age: 34, rating: 82, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Radamel Osorio", detailedPosition: .striker, age: 34, rating: 84),
            HistoricalPlayer(name: "Silvestre Nascimento", detailedPosition: .rightWing, age: 34, rating: 74),
            HistoricalPlayer(name: "James Bernal", detailedPosition: .attackingMid, age: 29, rating: 85, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Walter Salgueiro", detailedPosition: .centralMid, age: 35, rating: 68),
            HistoricalPlayer(name: "Maicon Cerezo", detailedPosition: .leftBack, age: 32, rating: 74),
            HistoricalPlayer(name: "Ruben Marotta", detailedPosition: .attackingMid, age: 32, rating: 77),
            HistoricalPlayer(name: "Rodrigo Nascimento", detailedPosition: .centreBack, age: 34, rating: 66),
        ],
    ]
}
