//
//  EuropeanSquads2010.swift
//  Retro Season Manager
//
//  Hand-authored 2010/11-era rosters for the same 8 foreign giant club
//  names used by EuropeanSquads2000.swift. Continuity names carry over
//  from the 2000 sheet where the same fictional player would plausibly
//  still be playing a decade on (e.g. Bassano, still at San Siro Rossoneri).
//

import Foundation

enum EuropeanSquads2010 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Bernabéu Whites": [
            HistoricalPlayer(name: "Iker Salaberri", detailedPosition: .goalkeeper, age: 29, rating: 90),
            HistoricalPlayer(name: "Antonio Novak", detailedPosition: .goalkeeper, age: 23, rating: 66),
            HistoricalPlayer(name: "Sergio Bernal", detailedPosition: .centreBack, age: 24, rating: 88, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Pepe Alvarenga", detailedPosition: .centreBack, age: 27, rating: 86),
            HistoricalPlayer(name: "Ricardo Salgueiro", detailedPosition: .centreBack, age: 32, rating: 82),
            HistoricalPlayer(name: "Marcelo Nascimento", detailedPosition: .leftBack, age: 22, rating: 84),
            HistoricalPlayer(name: "Alvaro Cerezo", detailedPosition: .rightBack, age: 27, rating: 78),
            HistoricalPlayer(name: "Xabi Bernal", detailedPosition: .holding, age: 28, rating: 88),
            HistoricalPlayer(name: "Sami Reinholt", detailedPosition: .holding, age: 23, rating: 82, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mesut Aydin", detailedPosition: .attackingMid, age: 21, rating: 87, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Angel Di Bello", detailedPosition: .rightWing, age: 22, rating: 85, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Cristiano Renaldo", detailedPosition: .leftWing, age: 25, rating: 96, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Gonzalo Tamudo", detailedPosition: .striker, age: 22, rating: 88),
            HistoricalPlayer(name: "Karim Idrissi", detailedPosition: .striker, age: 22, rating: 85),
            HistoricalPlayer(name: "Kaká Ribeiro", detailedPosition: .attackingMid, age: 28, rating: 84, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Lassana Diallo", detailedPosition: .holding, age: 25, rating: 76),
            HistoricalPlayer(name: "Raul Bernal", detailedPosition: .centreBack, age: 24, rating: 76),
            HistoricalPlayer(name: "Esteban Cerezo", detailedPosition: .attackingMid, age: 23, rating: 74),
        ],
        "Camp Blaugrana": [
            HistoricalPlayer(name: "Victor Salaberri", detailedPosition: .goalkeeper, age: 28, rating: 87),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .goalkeeper, age: 33, rating: 66),
            HistoricalPlayer(name: "Dani Cerezo", detailedPosition: .rightBack, age: 27, rating: 87),
            HistoricalPlayer(name: "Gerard Bernal", detailedPosition: .centreBack, age: 23, rating: 87),
            HistoricalPlayer(name: "Carles Reinholt", detailedPosition: .centreBack, age: 32, rating: 87),
            HistoricalPlayer(name: "Eric Diallo", detailedPosition: .leftBack, age: 30, rating: 82),
            HistoricalPlayer(name: "Sergio Salgueiro", detailedPosition: .holding, age: 21, rating: 84),
            HistoricalPlayer(name: "Xavier Puig", detailedPosition: .centralMid, age: 30, rating: 92, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Andres Cerezo", detailedPosition: .attackingMid, age: 26, rating: 92, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Lionel Mesi", detailedPosition: .rightWing, age: 23, rating: 97, secondaryPositions: [.striker, .attackingMid]),
            HistoricalPlayer(name: "David Cerezo", detailedPosition: .striker, age: 28, rating: 88, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Pedro Idrissi", detailedPosition: .rightWing, age: 23, rating: 84, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Javier Pellegrino", detailedPosition: .holding, age: 26, rating: 82, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Ibrahim Ndiaye", detailedPosition: .leftWing, age: 24, rating: 76),
            HistoricalPlayer(name: "Seydou Diallo", detailedPosition: .centralMid, age: 30, rating: 78),
            HistoricalPlayer(name: "Maxwell Salgueiro", detailedPosition: .leftBack, age: 28, rating: 75),
            HistoricalPlayer(name: "Bojan Novak", detailedPosition: .striker, age: 20, rating: 76),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .centralMid, age: 19, rating: 72),
        ],
        "Bavarian Reds": [
            HistoricalPlayer(name: "Hans-Jorg Reinholt", detailedPosition: .goalkeeper, age: 34, rating: 76),
            HistoricalPlayer(name: "Thomas Kral", detailedPosition: .goalkeeper, age: 24, rating: 66),
            HistoricalPlayer(name: "Philipp Krause", detailedPosition: .rightBack, age: 26, rating: 87, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Daniel Girard", detailedPosition: .centreBack, age: 32, rating: 80),
            HistoricalPlayer(name: "Martin Marotta", detailedPosition: .centreBack, age: 29, rating: 78),
            HistoricalPlayer(name: "Holger Fischer", detailedPosition: .centreBack, age: 21, rating: 76, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Bastian Wenzel", detailedPosition: .centralMid, age: 25, rating: 87, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Mark Bergman", detailedPosition: .holding, age: 33, rating: 80),
            HistoricalPlayer(name: "Arjen Vogel", detailedPosition: .rightWing, age: 26, rating: 90, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Franck Dubois", detailedPosition: .leftWing, age: 27, rating: 91, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Thomas Reuter", detailedPosition: .rightWing, age: 20, rating: 84, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Ivica Novak", detailedPosition: .striker, age: 30, rating: 78),
            HistoricalPlayer(name: "Toni Steiner", detailedPosition: .attackingMid, age: 20, rating: 79),
            HistoricalPlayer(name: "Miroslav Baumann", detailedPosition: .striker, age: 32, rating: 79),
            HistoricalPlayer(name: "Luiz Nascimento", detailedPosition: .holding, age: 23, rating: 74),
            HistoricalPlayer(name: "Anatoliy Larsen", detailedPosition: .holding, age: 31, rating: 76),
            HistoricalPlayer(name: "Diego Girard", detailedPosition: .leftBack, age: 20, rating: 68),
            HistoricalPlayer(name: "David Steiner", detailedPosition: .leftBack, age: 18, rating: 70, secondaryPositions: [.centralMid]),
        ],
        "Turin Bianconeri": [
            HistoricalPlayer(name: "Gianluigi Serrano", detailedPosition: .goalkeeper, age: 32, rating: 87),
            HistoricalPlayer(name: "Marco Rinaldi", detailedPosition: .goalkeeper, age: 34, rating: 68),
            HistoricalPlayer(name: "Giorgio Amadori", detailedPosition: .centreBack, age: 26, rating: 84, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Leonardo Fiore", detailedPosition: .centreBack, age: 23, rating: 80),
            HistoricalPlayer(name: "Andrea Rinaldi", detailedPosition: .centreBack, age: 29, rating: 79),
            HistoricalPlayer(name: "Nicola Serrano", detailedPosition: .centreBack, age: 34, rating: 72),
            HistoricalPlayer(name: "Zdenek Novak", detailedPosition: .rightBack, age: 30, rating: 73),
            HistoricalPlayer(name: "Claudio Fanti", detailedPosition: .centralMid, age: 24, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Milos Ivanov", detailedPosition: .rightWing, age: 25, rating: 79, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Felipe Nascimento", detailedPosition: .holding, age: 27, rating: 76),
            HistoricalPlayer(name: "Alessandro Fiore", detailedPosition: .striker, age: 36, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Vincenzo Amadori", detailedPosition: .striker, age: 29, rating: 74),
            HistoricalPlayer(name: "Amauri Salgueiro", detailedPosition: .striker, age: 29, rating: 76),
            HistoricalPlayer(name: "Diego Cerezo", detailedPosition: .attackingMid, age: 25, rating: 78, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Fabio Rinaldi", detailedPosition: .leftBack, age: 33, rating: 72),
            HistoricalPlayer(name: "Mauro Serrano", detailedPosition: .rightWing, age: 34, rating: 71),
            HistoricalPlayer(name: "Alessio Amadori", detailedPosition: .rightWing, age: 23, rating: 72),
            HistoricalPlayer(name: "Paolo Fanti", detailedPosition: .leftBack, age: 23, rating: 69),
        ],
        "San Siro Rossoneri": [
            HistoricalPlayer(name: "Christian Serrano", detailedPosition: .goalkeeper, age: 33, rating: 78),
            HistoricalPlayer(name: "Marco Novak", detailedPosition: .goalkeeper, age: 29, rating: 68),
            HistoricalPlayer(name: "Gianluca Rinaldi", detailedPosition: .rightBack, age: 33, rating: 76, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Alessandro Amadori", detailedPosition: .centreBack, age: 34, rating: 82),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .centreBack, age: 25, rating: 87),
            HistoricalPlayer(name: "Luca Fanti", detailedPosition: .leftBack, age: 28, rating: 72),
            HistoricalPlayer(name: "Massimo Serrano", detailedPosition: .holding, age: 33, rating: 77, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Andrea Pirlio", detailedPosition: .holding, age: 31, rating: 88, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Gennaro Rinaldi", detailedPosition: .centralMid, age: 32, rating: 75),
            HistoricalPlayer(name: "Clarence Vogel", detailedPosition: .attackingMid, age: 34, rating: 79),
            HistoricalPlayer(name: "Robinho Farias", detailedPosition: .rightWing, age: 26, rating: 82, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Zlatan Ibsen", detailedPosition: .striker, age: 29, rating: 90),
            HistoricalPlayer(name: "Alexandre Salgueiro", detailedPosition: .striker, age: 21, rating: 82),
            HistoricalPlayer(name: "Kevin-Prince Amara", detailedPosition: .attackingMid, age: 23, rating: 78, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mark Steiner", detailedPosition: .holding, age: 33, rating: 76),
            HistoricalPlayer(name: "Ignazio Fanti", detailedPosition: .rightBack, age: 24, rating: 71),
            HistoricalPlayer(name: "Filippo Amadori", detailedPosition: .striker, age: 37, rating: 71),
            HistoricalPlayer(name: "Antonio Rinaldi", detailedPosition: .attackingMid, age: 28, rating: 76, secondaryPositions: [.striker]),
        ],
        "San Siro Nerazzurri": [
            HistoricalPlayer(name: "Julio Cesar", detailedPosition: .goalkeeper, age: 30, rating: 88),
            HistoricalPlayer(name: "Luca Fanti", detailedPosition: .goalkeeper, age: 33, rating: 65),
            HistoricalPlayer(name: "Maicon Nascimento", detailedPosition: .rightBack, age: 28, rating: 87),
            HistoricalPlayer(name: "Lucio Cerezo", detailedPosition: .centreBack, age: 32, rating: 85),
            HistoricalPlayer(name: "Walter Marotta", detailedPosition: .centreBack, age: 32, rating: 84),
            HistoricalPlayer(name: "Cristian Belkacem", detailedPosition: .leftBack, age: 29, rating: 79, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Javier Pellegrino", detailedPosition: .holding, age: 36, rating: 84, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Esteban Bernal", detailedPosition: .holding, age: 30, rating: 84, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Wesley Reuter", detailedPosition: .attackingMid, age: 26, rating: 89, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Dejan Ivanov", detailedPosition: .centralMid, age: 32, rating: 78),
            HistoricalPlayer(name: "Goran Kral", detailedPosition: .rightWing, age: 27, rating: 78, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Samuel Ndiaye", detailedPosition: .striker, age: 29, rating: 89, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Diego Marotta", detailedPosition: .striker, age: 31, rating: 85),
            HistoricalPlayer(name: "Thiago Cerezo", detailedPosition: .holding, age: 28, rating: 79),
            HistoricalPlayer(name: "Ivan Salgueiro", detailedPosition: .centreBack, age: 34, rating: 72),
            HistoricalPlayer(name: "Fredy Idrissi", detailedPosition: .centralMid, age: 24, rating: 76),
            HistoricalPlayer(name: "Jonathan Girard", detailedPosition: .leftWing, age: 22, rating: 71),
            HistoricalPlayer(name: "Luc Fanti", detailedPosition: .striker, age: 18, rating: 63),
        ],
        "Amsterdam Godenzonen": [
            HistoricalPlayer(name: "Kenneth Reinholt", detailedPosition: .goalkeeper, age: 27, rating: 76),
            HistoricalPlayer(name: "Maarten Krause", detailedPosition: .goalkeeper, age: 27, rating: 79),
            HistoricalPlayer(name: "Toby Fischer", detailedPosition: .centreBack, age: 21, rating: 74, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Jan Wenzel", detailedPosition: .centreBack, age: 23, rating: 79, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Andre Bergman", detailedPosition: .centreBack, age: 33, rating: 75),
            HistoricalPlayer(name: "Gregory Steiner", detailedPosition: .rightBack, age: 22, rating: 76),
            HistoricalPlayer(name: "Urby Vogel", detailedPosition: .leftBack, age: 24, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Demy Novak", detailedPosition: .holding, age: 27, rating: 75),
            HistoricalPlayer(name: "Christian Larsen", detailedPosition: .attackingMid, age: 18, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Luuk Girard", detailedPosition: .striker, age: 20, rating: 74),
            HistoricalPlayer(name: "Miralem Ivanov", detailedPosition: .rightWing, age: 22, rating: 73),
            HistoricalPlayer(name: "Luis Bencosme", detailedPosition: .striker, age: 23, rating: 85, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Rasmus Bergman", detailedPosition: .centralMid, age: 25, rating: 71),
            HistoricalPlayer(name: "Vurnon Idrissi", detailedPosition: .centralMid, age: 21, rating: 70),
            HistoricalPlayer(name: "Marko Krause", detailedPosition: .centralMid, age: 23, rating: 68),
            HistoricalPlayer(name: "Thomas Wenzel", detailedPosition: .centreBack, age: 24, rating: 78),
            HistoricalPlayer(name: "Ismail Fanti", detailedPosition: .attackingMid, age: 21, rating: 66),
            HistoricalPlayer(name: "Jan Fischer", detailedPosition: .rightBack, age: 20, rating: 64),
        ],
        "Dragão Dragons": [
            HistoricalPlayer(name: "Helton Salgueiro", detailedPosition: .goalkeeper, age: 34, rating: 78),
            HistoricalPlayer(name: "Diego Cerezo", detailedPosition: .goalkeeper, age: 24, rating: 63),
            HistoricalPlayer(name: "Alvaro Marotta", detailedPosition: .leftBack, age: 24, rating: 75, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Rolando Nascimento", detailedPosition: .centreBack, age: 24, rating: 77),
            HistoricalPlayer(name: "Nicolas Bernal", detailedPosition: .centreBack, age: 22, rating: 75),
            HistoricalPlayer(name: "Cristian Ivanov", detailedPosition: .rightBack, age: 26, rating: 71),
            HistoricalPlayer(name: "Fernando Salgueiro", detailedPosition: .holding, age: 22, rating: 78),
            HistoricalPlayer(name: "Joao Cerezo", detailedPosition: .centralMid, age: 23, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Fredy Marotta", detailedPosition: .centralMid, age: 24, rating: 78),
            HistoricalPlayer(name: "Givanildo Marotta", detailedPosition: .rightWing, age: 24, rating: 84, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Radamel Osorio", detailedPosition: .striker, age: 24, rating: 86),
            HistoricalPlayer(name: "Silvestre Nascimento", detailedPosition: .rightWing, age: 24, rating: 76),
            HistoricalPlayer(name: "James Bernal", detailedPosition: .attackingMid, age: 19, rating: 76, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Walter Salgueiro", detailedPosition: .centralMid, age: 25, rating: 70),
            HistoricalPlayer(name: "Maicon Cerezo", detailedPosition: .leftBack, age: 22, rating: 68),
            HistoricalPlayer(name: "Ruben Marotta", detailedPosition: .attackingMid, age: 22, rating: 71),
            HistoricalPlayer(name: "Rodrigo Nascimento", detailedPosition: .centreBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Pedro Bernal", detailedPosition: .centreBack, age: 33, rating: 68),
        ],
    ]
}
