//
//  EuropeanSquads2000.swift
//  Retro Season Manager
//
//  Real first-team squads for the eight European giants that make up
//  GameStore's foreignPool (four are drawn into each save's Continental Cup),
//  as they stood at the start of the 2000/01 season. Same best-effort
//  approximation as HistoricalSquads2000 — accurate for the headline names,
//  lower confidence on squad depth for the less-documented clubs.
//

import Foundation

enum EuropeanSquads2000 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Bernabéu Whites": [
            HistoricalPlayer(name: "Iker Salaberri", detailedPosition: .goalkeeper, age: 19, rating: 78),
            HistoricalPlayer(name: "Kevin Reuter", detailedPosition: .goalkeeper, age: 28, rating: 74),
            HistoricalPlayer(name: "Roberto Miguel", detailedPosition: .leftBack, age: 27, rating: 89),
            HistoricalPlayer(name: "Marcus Solheim", detailedPosition: .rightBack, age: 25, rating: 79),
            HistoricalPlayer(name: "Kevin Boateng", detailedPosition: .centreBack, age: 32, rating: 85, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Hassan Rusev", detailedPosition: .centreBack, age: 24, rating: 74, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Henrik Brandt", detailedPosition: .centreBack, age: 27, rating: 68),
            HistoricalPlayer(name: "Wesley Radley", detailedPosition: .centreBack, age: 25, rating: 76, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Rasmus Wenzel", detailedPosition: .holding, age: 27, rating: 82),
            HistoricalPlayer(name: "Luca Sandham", detailedPosition: .holding, age: 32, rating: 83),
            HistoricalPlayer(name: "Rafael Hartmann", detailedPosition: .rightWing, age: 28, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Luís Camara", detailedPosition: .rightWing, age: 27, rating: 91, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Klaus Sandham", detailedPosition: .attackingMid, age: 24, rating: 78, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Jonas Halvorsen", detailedPosition: .leftWing, age: 23, rating: 70),
            HistoricalPlayer(name: "Raúl Antúnez", detailedPosition: .striker, age: 23, rating: 90),
            HistoricalPlayer(name: "Felipe Steiner", detailedPosition: .striker, age: 24, rating: 82),
            HistoricalPlayer(name: "Karim Karlsen", detailedPosition: .striker, age: 27, rating: 62),
            HistoricalPlayer(name: "Geremi Solano", detailedPosition: .striker, age: 22, rating: 65),
        ],
        "Camp Blaugrana": [
            HistoricalPlayer(name: "Tunde Winstanley", detailedPosition: .goalkeeper, age: 33, rating: 74),
            HistoricalPlayer(name: "Paul Halvorsen", detailedPosition: .goalkeeper, age: 18, rating: 58),
            HistoricalPlayer(name: "Erik Zeman", detailedPosition: .leftBack, age: 28, rating: 74),
            HistoricalPlayer(name: "Mateo Baumann", detailedPosition: .rightBack, age: 28, rating: 76),
            HistoricalPlayer(name: "Ryan Harding", detailedPosition: .centreBack, age: 30, rating: 80, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Lars Ndiaye", detailedPosition: .centreBack, age: 32, rating: 74),
            HistoricalPlayer(name: "Wesley Moreau", detailedPosition: .centreBack, age: 29, rating: 66, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Pietro Reuter", detailedPosition: .centreBack, age: 22, rating: 66),
            HistoricalPlayer(name: "Connor Sandham", detailedPosition: .centralMid, age: 30, rating: 79, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Marcus Sarr", detailedPosition: .holding, age: 30, rating: 80),
            HistoricalPlayer(name: "Sven Novak", detailedPosition: .rightWing, age: 30, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Emeka Camara", detailedPosition: .attackingMid, age: 25, rating: 72),
            HistoricalPlayer(name: "Xavier Puig", detailedPosition: .centralMid, age: 20, rating: 74, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Adam Castellan", detailedPosition: .leftWing, age: 27, rating: 82),
            HistoricalPlayer(name: "Rivaldo Nascimento", detailedPosition: .striker, age: 28, rating: 90, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Emil Fischer", detailedPosition: .striker, age: 24, rating: 84),
            HistoricalPlayer(name: "Idris Karlsen", detailedPosition: .striker, age: 27, rating: 60),
            HistoricalPlayer(name: "Carlos Rusev", detailedPosition: .striker, age: 22, rating: 68, secondaryPositions: [.rightWing]),
        ],
        "Bavarian Reds": [
            HistoricalPlayer(name: "Aaron Horvat", detailedPosition: .goalkeeper, age: 31, rating: 90),
            HistoricalPlayer(name: "Craig Dvorak", detailedPosition: .goalkeeper, age: 33, rating: 58),
            HistoricalPlayer(name: "Diego Halvorsen", detailedPosition: .leftBack, age: 30, rating: 82),
            HistoricalPlayer(name: "Mateo Diallo", detailedPosition: .rightBack, age: 23, rating: 76),
            HistoricalPlayer(name: "Felix Ashcroft", detailedPosition: .centreBack, age: 24, rating: 76),
            HistoricalPlayer(name: "Nico Bernard", detailedPosition: .centreBack, age: 30, rating: 74),
            HistoricalPlayer(name: "Kofi Dvorak", detailedPosition: .leftBack, age: 30, rating: 70, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Ivan Dubois", detailedPosition: .centreBack, age: 19, rating: 66, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Craig Larsen", detailedPosition: .centralMid, age: 32, rating: 85, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Idris Rousseau", detailedPosition: .attackingMid, age: 30, rating: 80, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "James Mensah", detailedPosition: .rightWing, age: 23, rating: 76),
            HistoricalPlayer(name: "Karim Salgueiro", detailedPosition: .holding, age: 26, rating: 74),
            HistoricalPlayer(name: "Mateo Novak", detailedPosition: .holding, age: 29, rating: 72, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Connor Moreau", detailedPosition: .centralMid, age: 32, rating: 68),
            HistoricalPlayer(name: "Daniel Berg", detailedPosition: .striker, age: 27, rating: 83),
            HistoricalPlayer(name: "Jonas Steiner", detailedPosition: .striker, age: 27, rating: 76),
            HistoricalPlayer(name: "Daniel Moreau", detailedPosition: .striker, age: 27, rating: 72),
            HistoricalPlayer(name: "Gordon Redfern", detailedPosition: .striker, age: 19, rating: 60),
        ],
        "Turin Bianconeri": [
            HistoricalPlayer(name: "Marco Winters", detailedPosition: .goalkeeper, age: 31, rating: 84),
            HistoricalPlayer(name: "Enzo Blackwood", detailedPosition: .goalkeeper, age: 37, rating: 56),
            HistoricalPlayer(name: "Diego Okafor", detailedPosition: .centreBack, age: 27, rating: 78),
            HistoricalPlayer(name: "Youssef Reuter", detailedPosition: .centreBack, age: 33, rating: 76),
            HistoricalPlayer(name: "Pietro Eriksson", detailedPosition: .centreBack, age: 29, rating: 78),
            HistoricalPlayer(name: "Dario Adeyemi", detailedPosition: .centreBack, age: 22, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Pietro Prentice", detailedPosition: .rightBack, age: 29, rating: 72),
            HistoricalPlayer(name: "Freddy Okafor", detailedPosition: .leftBack, age: 26, rating: 68),
            HistoricalPlayer(name: "Mateo Aldous", detailedPosition: .leftWing, age: 31, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Oskar Berg", detailedPosition: .holding, age: 27, rating: 85, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Craig Sandham", detailedPosition: .centralMid, age: 25, rating: 72, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Zinedine Belkacem", detailedPosition: .attackingMid, age: 28, rating: 93, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Karim Ashworth", detailedPosition: .centralMid, age: 28, rating: 58),
            HistoricalPlayer(name: "Kian Boateng", detailedPosition: .centralMid, age: 20, rating: 56),
            HistoricalPlayer(name: "Alessandro Fiore", detailedPosition: .striker, age: 26, rating: 88, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Adam Whitfield", detailedPosition: .striker, age: 27, rating: 82),
            HistoricalPlayer(name: "Lucas Hartmann", detailedPosition: .striker, age: 23, rating: 83),
            HistoricalPlayer(name: "Callum Berg", detailedPosition: .striker, age: 27, rating: 66),
        ],
        "San Siro Rossoneri": [
            HistoricalPlayer(name: "Diego Havel", detailedPosition: .goalkeeper, age: 23, rating: 74),
            HistoricalPlayer(name: "Gordon Vogel", detailedPosition: .goalkeeper, age: 35, rating: 62),
            HistoricalPlayer(name: "Paolo Rinaldi", detailedPosition: .leftBack, age: 32, rating: 90, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Yusuf Mensah", detailedPosition: .centreBack, age: 34, rating: 78),
            HistoricalPlayer(name: "Julio Teixeira", detailedPosition: .centreBack, age: 27, rating: 80),
            HistoricalPlayer(name: "Jamie Harding", detailedPosition: .rightBack, age: 28, rating: 72),
            HistoricalPlayer(name: "Pietro Dimitrov", detailedPosition: .leftBack, age: 27, rating: 68),
            HistoricalPlayer(name: "Felix Blackwood", detailedPosition: .centreBack, age: 22, rating: 70, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Anton Ashworth", detailedPosition: .centralMid, age: 29, rating: 80, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Petr Fischer", detailedPosition: .centralMid, age: 23, rating: 74, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Ethan Foulkes", detailedPosition: .attackingMid, age: 32, rating: 78),
            HistoricalPlayer(name: "Youssef Diallo", detailedPosition: .holding, age: 22, rating: 76),
            HistoricalPlayer(name: "Hector Ashworth", detailedPosition: .centralMid, age: 24, rating: 60),
            HistoricalPlayer(name: "Enzo Girard", detailedPosition: .holding, age: 36, rating: 56),
            HistoricalPlayer(name: "Leo Prewitt", detailedPosition: .striker, age: 34, rating: 78, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Vasil Marsh", detailedPosition: .striker, age: 32, rating: 76),
            HistoricalPlayer(name: "Andriy Petrenko", detailedPosition: .striker, age: 24, rating: 89),
            HistoricalPlayer(name: "Callum Fontaine", detailedPosition: .striker, age: 26, rating: 74),
        ],
        "San Siro Nerazzurri": [
            HistoricalPlayer(name: "Marco Bernard", detailedPosition: .goalkeeper, age: 20, rating: 74),
            HistoricalPlayer(name: "Emeka Sherrington", detailedPosition: .goalkeeper, age: 31, rating: 62),
            HistoricalPlayer(name: "Javier Pellegrino", detailedPosition: .rightBack, age: 27, rating: 84, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Dario Calloway", detailedPosition: .centreBack, age: 34, rating: 80, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Magnus Havel", detailedPosition: .centreBack, age: 27, rating: 68),
            HistoricalPlayer(name: "Wesley Redfern", detailedPosition: .centreBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Aaron Rousseau", detailedPosition: .centreBack, age: 20, rating: 58),
            HistoricalPlayer(name: "Emil Horvat", detailedPosition: .leftBack, age: 26, rating: 62),
            HistoricalPlayer(name: "Mateo Winters", detailedPosition: .rightWing, age: 28, rating: 72),
            HistoricalPlayer(name: "Thomas Foulkes", detailedPosition: .centralMid, age: 23, rating: 68),
            HistoricalPlayer(name: "Connor Sherrington", detailedPosition: .leftWing, age: 24, rating: 78, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Andrea Pirlio", detailedPosition: .centralMid, age: 21, rating: 72, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Salvatore Bianchi", detailedPosition: .centralMid, age: 25, rating: 65, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Viktor Whitfield", detailedPosition: .rightWing, age: 24, rating: 62, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Christian Marotta", detailedPosition: .striker, age: 27, rating: 88),
            HistoricalPlayer(name: "Ronaldo Basso", detailedPosition: .striker, age: 24, rating: 92),
            HistoricalPlayer(name: "Chidi Sarr", detailedPosition: .striker, age: 33, rating: 74),
            HistoricalPlayer(name: "Tomas Solheim", detailedPosition: .striker, age: 20, rating: 70),
        ],
        "Amsterdam Godenzonen": [
            HistoricalPlayer(name: "Neil Horvat", detailedPosition: .goalkeeper, age: 33, rating: 70),
            HistoricalPlayer(name: "Hugo Whitfield", detailedPosition: .goalkeeper, age: 20, rating: 58),
            HistoricalPlayer(name: "Pietro Larsen", detailedPosition: .leftBack, age: 26, rating: 66, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Scott Teixeira", detailedPosition: .centreBack, age: 19, rating: 70, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Henrik Fenwick", detailedPosition: .rightBack, age: 23, rating: 62),
            HistoricalPlayer(name: "Adam Radley", detailedPosition: .rightBack, age: 21, rating: 62),
            HistoricalPlayer(name: "Jonas Calder", detailedPosition: .centreBack, age: 24, rating: 62),
            HistoricalPlayer(name: "Ethan Prentice", detailedPosition: .leftBack, age: 19, rating: 58),
            HistoricalPlayer(name: "Neil Mendes", detailedPosition: .holding, age: 34, rating: 74, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Sven Horvat", detailedPosition: .rightWing, age: 21, rating: 72),
            HistoricalPlayer(name: "Oskar Kral", detailedPosition: .centralMid, age: 30, rating: 68, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Lars Nystrom", detailedPosition: .centralMid, age: 26, rating: 70, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Idris Toure", detailedPosition: .attackingMid, age: 17, rating: 68, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Owen Fenwick", detailedPosition: .centralMid, age: 22, rating: 62),
            HistoricalPlayer(name: "Dario Duarte", detailedPosition: .striker, age: 27, rating: 78),
            HistoricalPlayer(name: "James Foulkes", detailedPosition: .striker, age: 28, rating: 76),
            HistoricalPlayer(name: "Tomas Rusev", detailedPosition: .striker, age: 18, rating: 64),
            HistoricalPlayer(name: "Anders Redfern", detailedPosition: .striker, age: 24, rating: 56),
        ],
        "Dragão Dragons": [
            HistoricalPlayer(name: "Paul Brandt", detailedPosition: .goalkeeper, age: 31, rating: 82),
            HistoricalPlayer(name: "Jonas Salgueiro", detailedPosition: .goalkeeper, age: 34, rating: 66),
            HistoricalPlayer(name: "Bruno Havel", detailedPosition: .centreBack, age: 29, rating: 78),
            HistoricalPlayer(name: "Craig Ivanov", detailedPosition: .rightBack, age: 32, rating: 68),
            HistoricalPlayer(name: "Enzo Mensah", detailedPosition: .leftBack, age: 26, rating: 66),
            HistoricalPlayer(name: "Enzo Ndiaye", detailedPosition: .centreBack, age: 28, rating: 64),
            HistoricalPlayer(name: "Sven Berg", detailedPosition: .centreBack, age: 25, rating: 64),
            HistoricalPlayer(name: "Carlos Grantham", detailedPosition: .centreBack, age: 27, rating: 58),
            HistoricalPlayer(name: "Wesley Marsh", detailedPosition: .attackingMid, age: 22, rating: 80, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Callum Dimitrov", detailedPosition: .centralMid, age: 27, rating: 76, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Callum Lindqvist", detailedPosition: .centralMid, age: 25, rating: 66),
            HistoricalPlayer(name: "Marco Havel", detailedPosition: .rightWing, age: 28, rating: 70),
            HistoricalPlayer(name: "Marcus Boateng", detailedPosition: .leftWing, age: 24, rating: 62),
            HistoricalPlayer(name: "Lucas Brandt", detailedPosition: .centralMid, age: 26, rating: 62),
            HistoricalPlayer(name: "Jonas Castellan", detailedPosition: .striker, age: 26, rating: 74),
            HistoricalPlayer(name: "Pietro Steiner", detailedPosition: .striker, age: 27, rating: 68),
            HistoricalPlayer(name: "Lucas Lindqvist", detailedPosition: .striker, age: 25, rating: 60),
            HistoricalPlayer(name: "Anton Sherrington", detailedPosition: .striker, age: 23, rating: 54),
        ],
    ]
}
