//
//  HistoricalSquads2020.swift
//  Retro Season Manager
//
//  Hand-authored 2020/21-era rosters for the same 20 top-flight club
//  names used by HistoricalSquads2000.swift and HistoricalSquads2010.swift
//  — a further decade into the same fictional continuity. Built by aging
//  the 2010 sheet forward ten years: anyone who'd be 30 or younger on the
//  2010 sheet plausibly still has a career left in them, so carries the
//  same fictional name over (aged up, rating adjusted for where a ten-year
//  arc would realistically put them — a sharp rise for a 2010 teenager
//  hitting their prime, a gentle fade for a 2010 late-twenties player now
//  in their late thirties). Everyone older than that has retired in the
//  intervening decade and is replaced by a fresh fictional name in the
//  same style, seeded as a young player breaking into the side.
//

import Foundation

enum HistoricalSquads2020 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Old Trafford Reds": [
            HistoricalPlayer(name: "Tomasz Kral", detailedPosition: .goalkeeper, age: 38, rating: 60),
            HistoricalPlayer(name: "Nikolas Ferreira", detailedPosition: .goalkeeper, age: 21, rating: 74),
            HistoricalPlayer(name: "Rafael Almada", detailedPosition: .rightBack, age: 30, rating: 84, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Owen Radcliffe", detailedPosition: .centreBack, age: 20, rating: 76, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Nemanja Rusev", detailedPosition: .centreBack, age: 39, rating: 82),
            HistoricalPlayer(name: "Patrice Almada", detailedPosition: .leftBack, age: 39, rating: 79),
            HistoricalPlayer(name: "Chris Smalling", detailedPosition: .centreBack, age: 31, rating: 85, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Kacper Duda", detailedPosition: .leftWing, age: 20, rating: 77, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Michael Carrick", detailedPosition: .holding, age: 39, rating: 76),
            HistoricalPlayer(name: "Darren Fletcher", detailedPosition: .centralMid, age: 36, rating: 77, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Nani Almeida", detailedPosition: .rightWing, age: 34, rating: 81),
            HistoricalPlayer(name: "Antonio Valera", detailedPosition: .rightWing, age: 35, rating: 79, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ji-Hoon Park", detailedPosition: .rightWing, age: 39, rating: 68, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Wayne Kilbride", detailedPosition: .striker, age: 34, rating: 86, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Dimitar Yotov", detailedPosition: .striker, age: 39, rating: 78),
            HistoricalPlayer(name: "Javier Solis", detailedPosition: .striker, age: 32, rating: 88),
            HistoricalPlayer(name: "Elias Bramwell", detailedPosition: .attackingMid, age: 19, rating: 75, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Diogo Vieira", detailedPosition: .striker, age: 21, rating: 78),
        ],
        "Highbury": [
            HistoricalPlayer(name: "Manuel Salaberri", detailedPosition: .goalkeeper, age: 37, rating: 72),
            HistoricalPlayer(name: "Lukasz Kral", detailedPosition: .goalkeeper, age: 35, rating: 66),
            HistoricalPlayer(name: "Bacary Almada", detailedPosition: .rightBack, age: 37, rating: 76),
            HistoricalPlayer(name: "Laurent Belkacem", detailedPosition: .centreBack, age: 34, rating: 80, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Thomas Vermeulen", detailedPosition: .centreBack, age: 34, rating: 78),
            HistoricalPlayer(name: "Tobias Lindqvist", detailedPosition: .leftBack, age: 20, rating: 78),
            HistoricalPlayer(name: "Johan Djourou", detailedPosition: .centreBack, age: 33, rating: 80, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Alexandre Puig", detailedPosition: .holding, age: 33, rating: 88, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Francesc Aráoz", detailedPosition: .attackingMid, age: 33, rating: 92, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Samir Girard", detailedPosition: .centralMid, age: 33, rating: 85),
            HistoricalPlayer(name: "Jack Willoughby", detailedPosition: .centralMid, age: 28, rating: 85, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Tomas Rusev", detailedPosition: .centralMid, age: 34, rating: 72, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Andrei Volkov", detailedPosition: .leftWing, age: 39, rating: 76, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Samir Belhadj", detailedPosition: .leftWing, age: 33, rating: 90, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Theo Ashcroft", detailedPosition: .rightWing, age: 31, rating: 85),
            HistoricalPlayer(name: "Robin van Doren", detailedPosition: .striker, age: 37, rating: 81),
            HistoricalPlayer(name: "Marouane Idrissi", detailedPosition: .striker, age: 36, rating: 74),
            HistoricalPlayer(name: "Nicklas Nystrom", detailedPosition: .striker, age: 39, rating: 67, secondaryPositions: [.attackingMid]),
        ],
        "Mersey Reds": [
            HistoricalPlayer(name: "Pepe Salaberri", detailedPosition: .goalkeeper, age: 38, rating: 73),
            HistoricalPlayer(name: "Diego Cavani", detailedPosition: .goalkeeper, age: 36, rating: 63),
            HistoricalPlayer(name: "Glen Osgood", detailedPosition: .rightBack, age: 34, rating: 76),
            HistoricalPlayer(name: "Martin Novak", detailedPosition: .centreBack, age: 35, rating: 80),
            HistoricalPlayer(name: "Daniel Larsen", detailedPosition: .centreBack, age: 35, rating: 82),
            HistoricalPlayer(name: "Marcus Lindgren", detailedPosition: .centreBack, age: 21, rating: 76, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Emiliano Insua", detailedPosition: .leftBack, age: 31, rating: 79),
            HistoricalPlayer(name: "Lucas Fontaine", detailedPosition: .holding, age: 33, rating: 82, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Kofi Danso", detailedPosition: .attackingMid, age: 20, rating: 79, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Raul Costa", detailedPosition: .centralMid, age: 37, rating: 72),
            HistoricalPlayer(name: "Theo Falkner", detailedPosition: .rightWing, age: 20, rating: 75, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Maxi Fontaine", detailedPosition: .leftWing, age: 39, rating: 69, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Joe Radley", detailedPosition: .attackingMid, age: 38, rating: 67, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Fernando Casal", detailedPosition: .striker, age: 36, rating: 87, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Luis Bencosme", detailedPosition: .striker, age: 33, rating: 86, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "David Halloran", detailedPosition: .striker, age: 34, rating: 70),
            HistoricalPlayer(name: "Ryan Ashcroft", detailedPosition: .centreBack, age: 30, rating: 79, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Jonjo Fenwick", detailedPosition: .centralMid, age: 29, rating: 78),
        ],
        "Elland Athletic": [
            HistoricalPlayer(name: "Casper Ashdown", detailedPosition: .goalkeeper, age: 37, rating: 64),
            HistoricalPlayer(name: "Shane Fenshaw", detailedPosition: .goalkeeper, age: 33, rating: 65),
            HistoricalPlayer(name: "Andy Redfern", detailedPosition: .rightBack, age: 36, rating: 66),
            HistoricalPlayer(name: "Neill Calder", detailedPosition: .centreBack, age: 35, rating: 67),
            HistoricalPlayer(name: "Patrick Marshall", detailedPosition: .centreBack, age: 34, rating: 66),
            HistoricalPlayer(name: "Aidy Grantham", detailedPosition: .leftBack, age: 37, rating: 60),
            HistoricalPlayer(name: "Jonny Bishop", detailedPosition: .holding, age: 34, rating: 67),
            HistoricalPlayer(name: "Bradley Latham", detailedPosition: .centralMid, age: 32, rating: 74, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Robert Foy", detailedPosition: .centralMid, age: 38, rating: 60),
            HistoricalPlayer(name: "Davide Prentice", detailedPosition: .attackingMid, age: 34, rating: 68),
            HistoricalPlayer(name: "Max Osgood", detailedPosition: .leftWing, age: 31, rating: 74),
            HistoricalPlayer(name: "Jermaine Idrissi", detailedPosition: .rightWing, age: 35, rating: 66),
            HistoricalPlayer(name: "Luciano Vasconcelos", detailedPosition: .striker, age: 37, rating: 64),
            HistoricalPlayer(name: "Billy Truscott", detailedPosition: .striker, age: 33, rating: 72),
            HistoricalPlayer(name: "Robert Whitfield", detailedPosition: .striker, age: 39, rating: 59),
            HistoricalPlayer(name: "Tom Ndiaye", detailedPosition: .centreBack, age: 30, rating: 72),
            HistoricalPlayer(name: "Sam Calloway", detailedPosition: .rightBack, age: 30, rating: 71),
            HistoricalPlayer(name: "Kyle Girard", detailedPosition: .centralMid, age: 29, rating: 70),
        ],
        "Portman Rovers": [
            HistoricalPlayer(name: "Marton Fenshaw", detailedPosition: .goalkeeper, age: 39, rating: 61),
            HistoricalPlayer(name: "Alex Osborne", detailedPosition: .goalkeeper, age: 34, rating: 58),
            HistoricalPlayer(name: "Carlos Redfern", detailedPosition: .rightBack, age: 36, rating: 65),
            HistoricalPlayer(name: "Damien Calder", detailedPosition: .centreBack, age: 38, rating: 61),
            HistoricalPlayer(name: "Gareth Marshall", detailedPosition: .centreBack, age: 35, rating: 65),
            HistoricalPlayer(name: "Tommy Ashcroft", detailedPosition: .leftBack, age: 34, rating: 64),
            HistoricalPlayer(name: "Jack Grantham", detailedPosition: .holding, age: 33, rating: 71),
            HistoricalPlayer(name: "Owen Bishop", detailedPosition: .centralMid, age: 32, rating: 72),
            HistoricalPlayer(name: "Lee Latham", detailedPosition: .attackingMid, age: 37, rating: 61),
            HistoricalPlayer(name: "Jon Foy", detailedPosition: .centralMid, age: 35, rating: 64),
            HistoricalPlayer(name: "Grant Prentice", detailedPosition: .rightWing, age: 34, rating: 65),
            HistoricalPlayer(name: "David Osgood", detailedPosition: .leftWing, age: 36, rating: 64),
            HistoricalPlayer(name: "Connor Idrissi", detailedPosition: .striker, age: 32, rating: 74),
            HistoricalPlayer(name: "Michael Vasconcelos", detailedPosition: .striker, age: 38, rating: 62),
            HistoricalPlayer(name: "Kacper Nowicki", detailedPosition: .striker, age: 20, rating: 64),
            HistoricalPlayer(name: "Josh Ndiaye", detailedPosition: .centreBack, age: 29, rating: 70),
            HistoricalPlayer(name: "Ben Calloway", detailedPosition: .rightBack, age: 31, rating: 67),
            HistoricalPlayer(name: "Tyler Girard", detailedPosition: .centralMid, age: 30, rating: 69),
        ],
        "Stamford Blues": [
            HistoricalPlayer(name: "Petr Novotny", detailedPosition: .goalkeeper, age: 38, rating: 80),
            HistoricalPlayer(name: "Ross Fenshaw", detailedPosition: .goalkeeper, age: 34, rating: 64),
            HistoricalPlayer(name: "Branislav Kral", detailedPosition: .rightBack, age: 36, rating: 80, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "John Radley", detailedPosition: .centreBack, age: 39, rating: 81, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Alex Devereux", detailedPosition: .centreBack, age: 38, rating: 72),
            HistoricalPlayer(name: "Ashley Corrigan", detailedPosition: .leftBack, age: 39, rating: 75, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .rightBack, age: 37, rating: 69),
            HistoricalPlayer(name: "Michael Owusu", detailedPosition: .holding, age: 37, rating: 77, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "John Obidi", detailedPosition: .holding, age: 33, rating: 82, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Mateo Vidal", detailedPosition: .centralMid, age: 21, rating: 79, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ramires Nascimento", detailedPosition: .centralMid, age: 33, rating: 80),
            HistoricalPlayer(name: "Kai Bramwell", detailedPosition: .leftWing, age: 20, rating: 76, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Andrija Petrovic", detailedPosition: .striker, age: 22, rating: 83),
            HistoricalPlayer(name: "Romain Faucher", detailedPosition: .striker, age: 21, rating: 77),
            HistoricalPlayer(name: "Salomon Beheton", detailedPosition: .striker, age: 35, rating: 72, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Yuri Orlov", detailedPosition: .leftWing, age: 36, rating: 70),
            HistoricalPlayer(name: "Elton Mbeki", detailedPosition: .rightBack, age: 21, rating: 74),
            HistoricalPlayer(name: "Josh Prewitt", detailedPosition: .centralMid, age: 30, rating: 77),
        ],
        "Wearside": [
            HistoricalPlayer(name: "Craig Halvorsen", detailedPosition: .goalkeeper, age: 37, rating: 69),
            HistoricalPlayer(name: "Marton Fenwick", detailedPosition: .goalkeeper, age: 33, rating: 66),
            HistoricalPlayer(name: "Nedum Okafor", detailedPosition: .centreBack, age: 39, rating: 67),
            HistoricalPlayer(name: "Michael Blackwood", detailedPosition: .centreBack, age: 36, rating: 73),
            HistoricalPlayer(name: "John Adeyemi", detailedPosition: .centreBack, age: 38, rating: 65, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Kieran Redfern", detailedPosition: .leftBack, age: 34, rating: 69),
            HistoricalPlayer(name: "Phil Bishop", detailedPosition: .rightBack, age: 35, rating: 68),
            HistoricalPlayer(name: "Lee Ward", detailedPosition: .holding, age: 32, rating: 80, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Jordan Prentice", detailedPosition: .centralMid, age: 30, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "David Calloway", detailedPosition: .centralMid, age: 38, rating: 63),
            HistoricalPlayer(name: "Callum Vetch", detailedPosition: .attackingMid, age: 20, rating: 70, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ahmed Hassan", detailedPosition: .rightWing, age: 32, rating: 77),
            HistoricalPlayer(name: "Asamoah Mensah", detailedPosition: .striker, age: 34, rating: 80),
            HistoricalPlayer(name: "Darren Aldous", detailedPosition: .striker, age: 36, rating: 68, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Danny Foulkes", detailedPosition: .striker, age: 30, rating: 80, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Fraizer Latham", detailedPosition: .attackingMid, age: 31, rating: 74),
            HistoricalPlayer(name: "Idris Kamau", detailedPosition: .centreBack, age: 20, rating: 68),
            HistoricalPlayer(name: "Anton Grantham", detailedPosition: .holding, age: 35, rating: 63),
        ],
        "Aston Rovers": [
            HistoricalPlayer(name: "Marek Sobol", detailedPosition: .goalkeeper, age: 21, rating: 72),
            HistoricalPlayer(name: "Shay Osborne", detailedPosition: .goalkeeper, age: 35, rating: 60),
            HistoricalPlayer(name: "Alan Redfern", detailedPosition: .rightBack, age: 35, rating: 71),
            HistoricalPlayer(name: "Owen Fairclough", detailedPosition: .centreBack, age: 20, rating: 75),
            HistoricalPlayer(name: "James Marshall", detailedPosition: .centreBack, age: 36, rating: 74),
            HistoricalPlayer(name: "Stephen Blackwood", detailedPosition: .leftBack, age: 38, rating: 67),
            HistoricalPlayer(name: "Ciaran Foulkes", detailedPosition: .centreBack, age: 30, rating: 77, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Fabian Prentice", detailedPosition: .centralMid, age: 30, rating: 81),
            HistoricalPlayer(name: "Dries Tanghe", detailedPosition: .centralMid, age: 21, rating: 79, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Nigel Osgood", detailedPosition: .holding, age: 36, rating: 69),
            HistoricalPlayer(name: "Stewart Calloway", detailedPosition: .leftWing, age: 35, rating: 77, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ashley Aldous", detailedPosition: .rightWing, age: 35, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Gabriel Osei", detailedPosition: .striker, age: 34, rating: 77, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Kwame Boadu", detailedPosition: .striker, age: 21, rating: 76),
            HistoricalPlayer(name: "Igor Petrenko", detailedPosition: .striker, age: 22, rating: 74),
            HistoricalPlayer(name: "Marc Albrighton", detailedPosition: .rightWing, age: 30, rating: 77),
            HistoricalPlayer(name: "Barry Prentice", detailedPosition: .attackingMid, age: 30, rating: 76),
            HistoricalPlayer(name: "Nathan Osei", detailedPosition: .striker, age: 29, rating: 75),
        ],
        "Valley Rovers": [
            HistoricalPlayer(name: "Rob Halvorsen", detailedPosition: .goalkeeper, age: 34, rating: 66),
            HistoricalPlayer(name: "Ben Fenshaw", detailedPosition: .goalkeeper, age: 32, rating: 67),
            HistoricalPlayer(name: "Chris Redfern", detailedPosition: .rightBack, age: 30, rating: 75),
            HistoricalPlayer(name: "Denis Okoye", detailedPosition: .centreBack, age: 20, rating: 66),
            HistoricalPlayer(name: "Petar Simic", detailedPosition: .centralMid, age: 21, rating: 70, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Darren Osgood", detailedPosition: .attackingMid, age: 37, rating: 64),
            HistoricalPlayer(name: "Kelly Devereux", detailedPosition: .leftBack, age: 34, rating: 64),
            HistoricalPlayer(name: "Aled Vaughn", detailedPosition: .centreBack, age: 21, rating: 67, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .holding, age: 36, rating: 65),
            HistoricalPlayer(name: "Nicky Grantham", detailedPosition: .centralMid, age: 36, rating: 66),
            HistoricalPlayer(name: "Chris Ashcroft", detailedPosition: .striker, age: 34, rating: 65),
            HistoricalPlayer(name: "Kyle Prentice", detailedPosition: .striker, age: 32, rating: 71),
            HistoricalPlayer(name: "Momo Diakite", detailedPosition: .striker, age: 20, rating: 68),
            HistoricalPlayer(name: "Bradley Latham", detailedPosition: .centralMid, age: 34, rating: 63),
            HistoricalPlayer(name: "Leon Foy", detailedPosition: .striker, age: 34, rating: 66),
            HistoricalPlayer(name: "Scott Wagstaff", detailedPosition: .rightWing, age: 29, rating: 72),
            HistoricalPlayer(name: "Josh Bishop", detailedPosition: .leftWing, age: 35, rating: 62),
            HistoricalPlayer(name: "Rob Calloway", detailedPosition: .striker, age: 39, rating: 59),
        ],
        "Solent": [
            HistoricalPlayer(name: "Tom Sallis", detailedPosition: .goalkeeper, age: 20, rating: 64),
            HistoricalPlayer(name: "Bartosz Bialkowski", detailedPosition: .goalkeeper, age: 33, rating: 66),
            HistoricalPlayer(name: "Kwabena Osei", detailedPosition: .rightBack, age: 21, rating: 67),
            HistoricalPlayer(name: "Dan Ashdown", detailedPosition: .leftBack, age: 34, rating: 66),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .centreBack, age: 36, rating: 69),
            HistoricalPlayer(name: "Jason Foulkes", detailedPosition: .centreBack, age: 32, rating: 73),
            HistoricalPlayer(name: "Jonathan Grantham", detailedPosition: .striker, age: 35, rating: 65),
            HistoricalPlayer(name: "Adam Kral", detailedPosition: .attackingMid, age: 32, rating: 80, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Morgan Girard", detailedPosition: .holding, age: 30, rating: 80),
            HistoricalPlayer(name: "Milo Ferreira", detailedPosition: .centreBack, age: 20, rating: 65),
            HistoricalPlayer(name: "Papa Ndiaye", detailedPosition: .striker, age: 33, rating: 70),
            HistoricalPlayer(name: "Rickie Ashcroft", detailedPosition: .striker, age: 38, rating: 65),
            HistoricalPlayer(name: "David Fenwick", detailedPosition: .striker, age: 38, rating: 61),
            HistoricalPlayer(name: "Lee Calder", detailedPosition: .striker, age: 37, rating: 59),
            HistoricalPlayer(name: "Jason Blackwood", detailedPosition: .centralMid, age: 36, rating: 62),
            HistoricalPlayer(name: "Guly Salgueiro", detailedPosition: .rightWing, age: 33, rating: 69),
            HistoricalPlayer(name: "Dean Prentice", detailedPosition: .centralMid, age: 37, rating: 58),
            HistoricalPlayer(name: "Jos Bergman", detailedPosition: .centreBack, age: 37, rating: 61),
        ],
        "Tyneside": [
            HistoricalPlayer(name: "Tim Novak", detailedPosition: .goalkeeper, age: 32, rating: 80),
            HistoricalPlayer(name: "Espen Halvorsen", detailedPosition: .goalkeeper, age: 20, rating: 71),
            HistoricalPlayer(name: "Danny Redfern", detailedPosition: .rightBack, age: 33, rating: 74),
            HistoricalPlayer(name: "Fabricio Salaberri", detailedPosition: .centreBack, age: 38, rating: 72),
            HistoricalPlayer(name: "Steven Ward", detailedPosition: .centreBack, age: 34, rating: 71),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .leftBack, age: 34, rating: 74),
            HistoricalPlayer(name: "Cheick Diallo", detailedPosition: .holding, age: 34, rating: 76),
            HistoricalPlayer(name: "Joey Osgood", detailedPosition: .centralMid, age: 38, rating: 69, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Kevin Whitfield", detailedPosition: .centralMid, age: 38, rating: 70),
            HistoricalPlayer(name: "Hatem Idrissi", detailedPosition: .attackingMid, age: 33, rating: 83, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Jonas Bergman", detailedPosition: .rightWing, age: 37, rating: 66),
            HistoricalPlayer(name: "Andy Fenner", detailedPosition: .striker, age: 31, rating: 89),
            HistoricalPlayer(name: "Leon Truscott", detailedPosition: .striker, age: 32, rating: 74),
            HistoricalPlayer(name: "Shola Chastain", detailedPosition: .striker, age: 38, rating: 64),
            HistoricalPlayer(name: "Youssef Amrani", detailedPosition: .leftWing, age: 20, rating: 72),
            HistoricalPlayer(name: "James Osborne", detailedPosition: .rightBack, age: 35, rating: 63),
            HistoricalPlayer(name: "Alan Truscott", detailedPosition: .striker, age: 39, rating: 61, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Sanchez Foulkes", detailedPosition: .leftWing, age: 29, rating: 72),
        ],
        "White Hart Athletic": [
            HistoricalPlayer(name: "Anders Kjeldsen", detailedPosition: .goalkeeper, age: 22, rating: 77),
            HistoricalPlayer(name: "Milan Vukovic", detailedPosition: .goalkeeper, age: 20, rating: 66),
            HistoricalPlayer(name: "Vedran Novak", detailedPosition: .rightBack, age: 35, rating: 75),
            HistoricalPlayer(name: "Michael Truscott", detailedPosition: .centreBack, age: 37, rating: 73),
            HistoricalPlayer(name: "Joaquin Ferraz", detailedPosition: .centreBack, age: 21, rating: 78),
            HistoricalPlayer(name: "Benoit Diallo", detailedPosition: .leftBack, age: 36, rating: 74),
            HistoricalPlayer(name: "Younes Idrissi", detailedPosition: .centreBack, age: 34, rating: 71),
            HistoricalPlayer(name: "Gareth Baile", detailedPosition: .leftWing, age: 31, rating: 94, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Luka Kral", detailedPosition: .attackingMid, age: 35, rating: 85, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Rafael Doren", detailedPosition: .attackingMid, age: 37, rating: 76, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Wilson Aráoz", detailedPosition: .holding, age: 36, rating: 73),
            HistoricalPlayer(name: "Aaron Prescott", detailedPosition: .rightWing, age: 33, rating: 83),
            HistoricalPlayer(name: "Peter Foy", detailedPosition: .striker, age: 39, rating: 71),
            HistoricalPlayer(name: "Jermain Prescott", detailedPosition: .striker, age: 38, rating: 69),
            HistoricalPlayer(name: "Roman Orlov", detailedPosition: .striker, age: 38, rating: 65),
            HistoricalPlayer(name: "Tom Latham", detailedPosition: .centralMid, age: 33, rating: 79, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Niko Novak", detailedPosition: .attackingMid, age: 35, rating: 72),
            HistoricalPlayer(name: "Sandro Nascimento", detailedPosition: .holding, age: 31, rating: 76),
        ],
        "Filbert Foxes": [
            HistoricalPlayer(name: "Chris Fenshaw", detailedPosition: .goalkeeper, age: 37, rating: 58),
            HistoricalPlayer(name: "Kasper Larsen", detailedPosition: .goalkeeper, age: 33, rating: 72),
            HistoricalPlayer(name: "Jack Redfern", detailedPosition: .centreBack, age: 34, rating: 64),
            HistoricalPlayer(name: "Filip Kowalczyk", detailedPosition: .leftBack, age: 20, rating: 64),
            HistoricalPlayer(name: "Tunde Balogun", detailedPosition: .leftBack, age: 21, rating: 62),
            HistoricalPlayer(name: "Andy Ashcroft", detailedPosition: .centralMid, age: 31, rating: 74),
            HistoricalPlayer(name: "Richie Grantham", detailedPosition: .centralMid, age: 39, rating: 60),
            HistoricalPlayer(name: "Neil Bishop", detailedPosition: .attackingMid, age: 36, rating: 65),
            HistoricalPlayer(name: "Lloyd Osgood", detailedPosition: .leftWing, age: 37, rating: 61),
            HistoricalPlayer(name: "Jermaine Whitlock", detailedPosition: .striker, age: 36, rating: 69),
            HistoricalPlayer(name: "Rasmus Holt", detailedPosition: .striker, age: 21, rating: 65),
            HistoricalPlayer(name: "Paul Calloway", detailedPosition: .attackingMid, age: 35, rating: 63),
            HistoricalPlayer(name: "Matt Prentice", detailedPosition: .striker, age: 34, rating: 66),
            HistoricalPlayer(name: "Michael Foy", detailedPosition: .centreBack, age: 32, rating: 70),
            HistoricalPlayer(name: "Aleksandar Tunchev", detailedPosition: .rightBack, age: 38, rating: 56),
            HistoricalPlayer(name: "Sean Aldous", detailedPosition: .centreBack, age: 35, rating: 62),
            HistoricalPlayer(name: "Max Idrissi", detailedPosition: .rightWing, age: 32, rating: 72),
            HistoricalPlayer(name: "Danny Purslow", detailedPosition: .centreBack, age: 20, rating: 60),
        ],
        "Teesside": [
            HistoricalPlayer(name: "Jason Fenshaw", detailedPosition: .goalkeeper, age: 30, rating: 72),
            HistoricalPlayer(name: "Ross Redfern", detailedPosition: .goalkeeper, age: 35, rating: 63),
            HistoricalPlayer(name: "Justin Ashcroft", detailedPosition: .rightBack, age: 35, rating: 64),
            HistoricalPlayer(name: "Matthew Calder", detailedPosition: .centreBack, age: 34, rating: 63),
            HistoricalPlayer(name: "Rhys Marshall", detailedPosition: .centreBack, age: 31, rating: 70),
            HistoricalPlayer(name: "Andrew Osgood", detailedPosition: .leftBack, age: 34, rating: 64),
            HistoricalPlayer(name: "Denys Lypko", detailedPosition: .centralMid, age: 20, rating: 62),
            HistoricalPlayer(name: "Adam Latham", detailedPosition: .rightWing, age: 32, rating: 80, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Gary Foy", detailedPosition: .centralMid, age: 37, rating: 60),
            HistoricalPlayer(name: "Kris Prentice", detailedPosition: .striker, age: 36, rating: 67),
            HistoricalPlayer(name: "Scott Bishop", detailedPosition: .striker, age: 36, rating: 66),
            HistoricalPlayer(name: "Tarmo Larsen", detailedPosition: .striker, age: 33, rating: 66),
            HistoricalPlayer(name: "Faris Idrissi", detailedPosition: .holding, age: 32, rating: 69),
            HistoricalPlayer(name: "Joe Calloway", detailedPosition: .leftBack, age: 29, rating: 71),
            HistoricalPlayer(name: "Bilal Rachid", detailedPosition: .leftWing, age: 20, rating: 63),
            HistoricalPlayer(name: "Willo Ashdown", detailedPosition: .attackingMid, age: 34, rating: 60),
            HistoricalPlayer(name: "David Grantham", detailedPosition: .centreBack, age: 35, rating: 63),
            HistoricalPlayer(name: "Marvin Vasconcelos", detailedPosition: .striker, age: 32, rating: 71),
        ],
        "Upton Athletic": [
            HistoricalPlayer(name: "Petros Antoniou", detailedPosition: .goalkeeper, age: 21, rating: 70),
            HistoricalPlayer(name: "Sam Whitby", detailedPosition: .goalkeeper, age: 19, rating: 64),
            HistoricalPlayer(name: "Herita Ndiaye", detailedPosition: .leftBack, age: 37, rating: 61),
            HistoricalPlayer(name: "Reece Coldwell", detailedPosition: .centreBack, age: 20, rating: 70),
            HistoricalPlayer(name: "James Marshall", detailedPosition: .centreBack, age: 31, rating: 74),
            HistoricalPlayer(name: "Guy Idrissi", detailedPosition: .rightBack, age: 38, rating: 62),
            HistoricalPlayer(name: "Youri Bakker", detailedPosition: .holding, age: 21, rating: 76),
            HistoricalPlayer(name: "Mark Latham", detailedPosition: .centralMid, age: 33, rating: 79),
            HistoricalPlayer(name: "Ilya Sorokin", detailedPosition: .rightWing, age: 20, rating: 68),
            HistoricalPlayer(name: "Valon Novak", detailedPosition: .centralMid, age: 35, rating: 68),
            HistoricalPlayer(name: "Victor Osei", detailedPosition: .leftWing, age: 32, rating: 78, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Cauã Ribeiro", detailedPosition: .striker, age: 21, rating: 72),
            HistoricalPlayer(name: "Carlton Whitfield", detailedPosition: .striker, age: 37, rating: 66),
            HistoricalPlayer(name: "Demba Mensah", detailedPosition: .striker, age: 35, rating: 74),
            HistoricalPlayer(name: "Zavon Foulkes", detailedPosition: .rightWing, age: 32, rating: 70),
            HistoricalPlayer(name: "Radoslav Ivanov", detailedPosition: .holding, age: 39, rating: 57),
            HistoricalPlayer(name: "Danny Osafo", detailedPosition: .leftBack, age: 20, rating: 65),
            HistoricalPlayer(name: "Jack Bishop", detailedPosition: .centralMid, age: 31, rating: 71),
        ],
        "Goodison Blues": [
            HistoricalPlayer(name: "Rasmus Eide", detailedPosition: .goalkeeper, age: 21, rating: 74),
            HistoricalPlayer(name: "Jan Novak", detailedPosition: .goalkeeper, age: 36, rating: 61),
            HistoricalPlayer(name: "Tony Ashcroft", detailedPosition: .rightBack, age: 39, rating: 64),
            HistoricalPlayer(name: "Phil Latham", detailedPosition: .centreBack, age: 38, rating: 72),
            HistoricalPlayer(name: "Igor Vasilenko", detailedPosition: .centreBack, age: 20, rating: 74),
            HistoricalPlayer(name: "Leighton Calder", detailedPosition: .leftBack, age: 35, rating: 79),
            HistoricalPlayer(name: "Owen Trelawny", detailedPosition: .centreBack, age: 20, rating: 71, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Marouane Amrani", detailedPosition: .attackingMid, age: 32, rating: 85, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Mikel Puig", detailedPosition: .attackingMid, age: 38, rating: 77, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Leon Foy", detailedPosition: .centralMid, age: 39, rating: 67),
            HistoricalPlayer(name: "Steven Botha", detailedPosition: .leftWing, age: 38, rating: 71, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Diniyar Orlov", detailedPosition: .rightWing, age: 36, rating: 70),
            HistoricalPlayer(name: "Diego Ferraz", detailedPosition: .attackingMid, age: 20, rating: 76, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Yakubu Osei", detailedPosition: .striker, age: 37, rating: 69),
            HistoricalPlayer(name: "Kaan Yildiz", detailedPosition: .striker, age: 21, rating: 73),
            HistoricalPlayer(name: "Jack Latham", detailedPosition: .centralMid, age: 29, rating: 79),
            HistoricalPlayer(name: "Seamus Foy", detailedPosition: .rightBack, age: 31, rating: 74),
            HistoricalPlayer(name: "Jermaine Truscott", detailedPosition: .striker, age: 37, rating: 61),
        ],
        "Pride Rams": [
            HistoricalPlayer(name: "Stephen Fenshaw", detailedPosition: .goalkeeper, age: 37, rating: 58),
            HistoricalPlayer(name: "Saul Redfern", detailedPosition: .goalkeeper, age: 34, rating: 58),
            HistoricalPlayer(name: "Przemyslaw Kazimierczak", detailedPosition: .goalkeeper, age: 34, rating: 58),
            HistoricalPlayer(name: "Miles Ashcroft", detailedPosition: .centreBack, age: 30, rating: 73),
            HistoricalPlayer(name: "Jason Calder", detailedPosition: .centreBack, age: 35, rating: 63),
            HistoricalPlayer(name: "Shaun Marshall", detailedPosition: .rightBack, age: 36, rating: 64),
            HistoricalPlayer(name: "Stephen Grantham", detailedPosition: .centralMid, age: 37, rating: 58),
            HistoricalPlayer(name: "Kris Bishop", detailedPosition: .leftWing, age: 37, rating: 62, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Nathan Osgood", detailedPosition: .striker, age: 38, rating: 57),
            HistoricalPlayer(name: "Marcin Wojcik", detailedPosition: .centralMid, age: 20, rating: 60),
            HistoricalPlayer(name: "Denzel Achterberg", detailedPosition: .striker, age: 20, rating: 61),
            HistoricalPlayer(name: "John Prentice", detailedPosition: .rightBack, age: 31, rating: 68),
            HistoricalPlayer(name: "Chris Grantham", detailedPosition: .centreBack, age: 39, rating: 56),
            HistoricalPlayer(name: "Youssouf Traore", detailedPosition: .leftBack, age: 20, rating: 59),
            HistoricalPlayer(name: "Ben Foulkes", detailedPosition: .attackingMid, age: 31, rating: 68),
            HistoricalPlayer(name: "Theo Vasconcelos", detailedPosition: .striker, age: 30, rating: 72),
            HistoricalPlayer(name: "Jake Osborne", detailedPosition: .centreBack, age: 36, rating: 60),
            HistoricalPlayer(name: "Conor Ndiaye", detailedPosition: .striker, age: 32, rating: 67),
        ],
        "Etihad Blues": [
            HistoricalPlayer(name: "Joe Ashdown", detailedPosition: .goalkeeper, age: 33, rating: 87),
            HistoricalPlayer(name: "Bartek Nowak", detailedPosition: .goalkeeper, age: 21, rating: 76),
            HistoricalPlayer(name: "Pablo Cerezo", detailedPosition: .rightBack, age: 35, rating: 76),
            HistoricalPlayer(name: "Vincent Amara", detailedPosition: .centreBack, age: 34, rating: 84),
            HistoricalPlayer(name: "Joleon Ashcroft", detailedPosition: .centreBack, age: 37, rating: 71),
            HistoricalPlayer(name: "Aleksandar Ivanov", detailedPosition: .leftBack, age: 34, rating: 74),
            HistoricalPlayer(name: "Micah Calder", detailedPosition: .rightBack, age: 32, rating: 80, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Kolo Diallo", detailedPosition: .centreBack, age: 39, rating: 72),
            HistoricalPlayer(name: "Nigel Bergman", detailedPosition: .holding, age: 35, rating: 77),
            HistoricalPlayer(name: "Gareth Osgood", detailedPosition: .holding, age: 39, rating: 73, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "David Puig", detailedPosition: .attackingMid, age: 34, rating: 85, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Youssef Karim", detailedPosition: .holding, age: 21, rating: 79, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Carlos Marotta", detailedPosition: .striker, age: 36, rating: 87, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Mario Rinaldi", detailedPosition: .striker, age: 30, rating: 86),
            HistoricalPlayer(name: "Emmanuel Diallo", detailedPosition: .striker, age: 36, rating: 76),
            HistoricalPlayer(name: "James Truscott", detailedPosition: .rightWing, age: 34, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Adam Foy", detailedPosition: .leftWing, age: 33, rating: 78),
            HistoricalPlayer(name: "Edin Kral", detailedPosition: .striker, age: 34, rating: 80),
        ],
        "Highfield Athletic": [
            HistoricalPlayer(name: "Keiren Osborne", detailedPosition: .goalkeeper, age: 35, rating: 63),
            HistoricalPlayer(name: "Chris Fenshaw", detailedPosition: .goalkeeper, age: 32, rating: 66),
            HistoricalPlayer(name: "Lee Fenshaw", detailedPosition: .goalkeeper, age: 36, rating: 60),
            HistoricalPlayer(name: "Kacper Zielinski", detailedPosition: .rightBack, age: 20, rating: 60),
            HistoricalPlayer(name: "Elliott Calder", detailedPosition: .centreBack, age: 36, rating: 62),
            HistoricalPlayer(name: "Sammy Grantham", detailedPosition: .centralMid, age: 36, rating: 63),
            HistoricalPlayer(name: "Gary Bishop", detailedPosition: .holding, age: 32, rating: 69),
            HistoricalPlayer(name: "Carl Latham", detailedPosition: .attackingMid, age: 37, rating: 59),
            HistoricalPlayer(name: "Freddy Prentice", detailedPosition: .striker, age: 36, rating: 63),
            HistoricalPlayer(name: "Clive Foy", detailedPosition: .striker, age: 39, rating: 56),
            HistoricalPlayer(name: "Michael Idrissi", detailedPosition: .leftWing, age: 38, rating: 57),
            HistoricalPlayer(name: "David Osgood", detailedPosition: .centralMid, age: 35, rating: 61),
            HistoricalPlayer(name: "Marlon Truscott", detailedPosition: .striker, age: 39, rating: 59),
            HistoricalPlayer(name: "Charlie Vasconcelos", detailedPosition: .centralMid, age: 34, rating: 59),
            HistoricalPlayer(name: "Cyrus Foulkes", detailedPosition: .rightBack, age: 28, rating: 67),
            HistoricalPlayer(name: "Jermaine Ndiaye", detailedPosition: .centreBack, age: 37, rating: 54),
            HistoricalPlayer(name: "Franck Girard", detailedPosition: .leftWing, age: 31, rating: 67),
            HistoricalPlayer(name: "Gavin Calloway", detailedPosition: .centreBack, age: 30, rating: 68),
        ],
        "Valley Parade": [
            HistoricalPlayer(name: "Simon Osborne", detailedPosition: .goalkeeper, age: 30, rating: 69),
            HistoricalPlayer(name: "Jon Fenshaw", detailedPosition: .goalkeeper, age: 32, rating: 67),
            HistoricalPlayer(name: "Scott Fenshaw", detailedPosition: .goalkeeper, age: 32, rating: 64),
            HistoricalPlayer(name: "Luke Ashcroft", detailedPosition: .centreBack, age: 35, rating: 59),
            HistoricalPlayer(name: "Zesh Idrissi", detailedPosition: .centreBack, age: 37, rating: 55),
            HistoricalPlayer(name: "Denis Halko", detailedPosition: .rightBack, age: 20, rating: 57),
            HistoricalPlayer(name: "Lee Latham", detailedPosition: .holding, age: 38, rating: 54),
            HistoricalPlayer(name: "Gareth Prentice", detailedPosition: .rightWing, age: 32, rating: 68),
            HistoricalPlayer(name: "James Foy", detailedPosition: .striker, age: 32, rating: 68),
            HistoricalPlayer(name: "Ollie Fairweather", detailedPosition: .centralMid, age: 20, rating: 58),
            HistoricalPlayer(name: "Momodou Jallow", detailedPosition: .striker, age: 20, rating: 58),
            HistoricalPlayer(name: "Bruno Alencar", detailedPosition: .striker, age: 20, rating: 57),
            HistoricalPlayer(name: "Robbie Truscott", detailedPosition: .leftBack, age: 30, rating: 67),
            HistoricalPlayer(name: "Tom Ndiaye", detailedPosition: .holding, age: 28, rating: 66),
            HistoricalPlayer(name: "Louis Girard", detailedPosition: .striker, age: 28, rating: 65),
            HistoricalPlayer(name: "Craig Bishop", detailedPosition: .centralMid, age: 33, rating: 65),
            HistoricalPlayer(name: "Omar Idrissi", detailedPosition: .leftWing, age: 37, rating: 53),
            HistoricalPlayer(name: "Kyel Foulkes", detailedPosition: .leftWing, age: 31, rating: 66),
        ],
    ]
}
