//
//  HistoricalSquads2010.swift
//  Retro Season Manager
//
//  Hand-authored 2010/11-era rosters for the same 20 top-flight club
//  names used by HistoricalSquads2000.swift — same fictional club
//  identities, a decade further into their (fictional) careers. Where a
//  player also appeared on the 2000 sheet and would plausibly still be
//  playing a decade on, the same fictional name carries over (aged up);
//  everyone else is a fresh fictional name in the same style.
//

import Foundation

enum HistoricalSquads2010 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Old Trafford Reds": [
            HistoricalPlayer(name: "Edwin Doren", detailedPosition: .goalkeeper, age: 39, rating: 84),
            HistoricalPlayer(name: "Tomasz Kral", detailedPosition: .goalkeeper, age: 28, rating: 68),
            HistoricalPlayer(name: "Rafael Almada", detailedPosition: .rightBack, age: 20, rating: 76, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Ian Castellan", detailedPosition: .centreBack, age: 38, rating: 74, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Nemanja Rusev", detailedPosition: .centreBack, age: 29, rating: 90),
            HistoricalPlayer(name: "Patrice Almada", detailedPosition: .leftBack, age: 29, rating: 87),
            HistoricalPlayer(name: "Chris Smallwood", detailedPosition: .centreBack, age: 21, rating: 78, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Ryan Merrick", detailedPosition: .leftWing, age: 37, rating: 79, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Paul Kenwright", detailedPosition: .centralMid, age: 35, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Michael Kerrigan", detailedPosition: .holding, age: 29, rating: 84),
            HistoricalPlayer(name: "Darren Fenwick", detailedPosition: .centralMid, age: 26, rating: 80, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Nani Almeida", detailedPosition: .rightWing, age: 24, rating: 85),
            HistoricalPlayer(name: "Antonio Valera", detailedPosition: .rightWing, age: 25, rating: 84, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ji-Hoon Park", detailedPosition: .rightWing, age: 29, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Wayne Kilbride", detailedPosition: .striker, age: 24, rating: 91, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Dimitar Yotov", detailedPosition: .striker, age: 29, rating: 87),
            HistoricalPlayer(name: "Javier Solis", detailedPosition: .striker, age: 22, rating: 82),
            HistoricalPlayer(name: "Michael Prescott", detailedPosition: .striker, age: 30, rating: 78, secondaryPositions: [.attackingMid]),
        ],
        "Highbury": [
            HistoricalPlayer(name: "Manuel Salaberri", detailedPosition: .goalkeeper, age: 27, rating: 79),
            HistoricalPlayer(name: "Lukasz Kral", detailedPosition: .goalkeeper, age: 25, rating: 68),
            HistoricalPlayer(name: "Bacary Almada", detailedPosition: .rightBack, age: 27, rating: 83),
            HistoricalPlayer(name: "Laurent Belkacem", detailedPosition: .centreBack, age: 24, rating: 82, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Thomas Vermeulen", detailedPosition: .centreBack, age: 24, rating: 80),
            HistoricalPlayer(name: "Gael Devereux", detailedPosition: .leftBack, age: 30, rating: 79),
            HistoricalPlayer(name: "Johan Djourou", detailedPosition: .centreBack, age: 23, rating: 74, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Alexandre Puig", detailedPosition: .holding, age: 23, rating: 84, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Francesc Aráoz", detailedPosition: .attackingMid, age: 23, rating: 89, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Samir Girard", detailedPosition: .centralMid, age: 23, rating: 79),
            HistoricalPlayer(name: "Jack Willoughby", detailedPosition: .centralMid, age: 18, rating: 76, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Tomas Rusev", detailedPosition: .centralMid, age: 24, rating: 74, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Andrei Volkov", detailedPosition: .leftWing, age: 29, rating: 83, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Samir Belhadj", detailedPosition: .leftWing, age: 23, rating: 84, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Theo Ashcroft", detailedPosition: .rightWing, age: 21, rating: 79),
            HistoricalPlayer(name: "Robin van Doren", detailedPosition: .striker, age: 27, rating: 88),
            HistoricalPlayer(name: "Marouane Idrissi", detailedPosition: .striker, age: 26, rating: 76),
            HistoricalPlayer(name: "Nicklas Nystrom", detailedPosition: .striker, age: 29, rating: 74, secondaryPositions: [.attackingMid]),
        ],
        "Mersey Reds": [
            HistoricalPlayer(name: "Pepe Salaberri", detailedPosition: .goalkeeper, age: 28, rating: 80),
            HistoricalPlayer(name: "Diego Cavani", detailedPosition: .goalkeeper, age: 26, rating: 65),
            HistoricalPlayer(name: "Glen Osgood", detailedPosition: .rightBack, age: 24, rating: 78),
            HistoricalPlayer(name: "Martin Novak", detailedPosition: .centreBack, age: 25, rating: 82),
            HistoricalPlayer(name: "Daniel Larsen", detailedPosition: .centreBack, age: 25, rating: 84),
            HistoricalPlayer(name: "Jamie Rousell", detailedPosition: .centreBack, age: 32, rating: 75, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Emiliano Insua", detailedPosition: .leftBack, age: 21, rating: 73),
            HistoricalPlayer(name: "Lucas Fontaine", detailedPosition: .holding, age: 23, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Steven Halloran", detailedPosition: .attackingMid, age: 30, rating: 88, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Raul Costa", detailedPosition: .centralMid, age: 27, rating: 79),
            HistoricalPlayer(name: "Dirk Bergman", detailedPosition: .rightWing, age: 30, rating: 80, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Maxi Fontaine", detailedPosition: .leftWing, age: 29, rating: 76, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Joe Radley", detailedPosition: .attackingMid, age: 28, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Fernando Casal", detailedPosition: .striker, age: 26, rating: 89, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Luis Bencosme", detailedPosition: .striker, age: 23, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "David Halloran", detailedPosition: .striker, age: 24, rating: 72),
            HistoricalPlayer(name: "Ryan Ashcroft", detailedPosition: .centreBack, age: 20, rating: 70, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Jonjo Fenwick", detailedPosition: .centralMid, age: 19, rating: 69),
        ],
        "Elland Athletic": [
            HistoricalPlayer(name: "Casper Ashdown", detailedPosition: .goalkeeper, age: 27, rating: 71),
            HistoricalPlayer(name: "Shane Fenshaw", detailedPosition: .goalkeeper, age: 23, rating: 61),
            HistoricalPlayer(name: "Andy Redfern", detailedPosition: .rightBack, age: 26, rating: 68),
            HistoricalPlayer(name: "Neill Calder", detailedPosition: .centreBack, age: 25, rating: 69),
            HistoricalPlayer(name: "Patrick Marshall", detailedPosition: .centreBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Aidy Grantham", detailedPosition: .leftBack, age: 27, rating: 67),
            HistoricalPlayer(name: "Jonny Bishop", detailedPosition: .holding, age: 24, rating: 69),
            HistoricalPlayer(name: "Bradley Latham", detailedPosition: .centralMid, age: 22, rating: 68, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Robert Foy", detailedPosition: .centralMid, age: 28, rating: 67),
            HistoricalPlayer(name: "Davide Prentice", detailedPosition: .attackingMid, age: 24, rating: 70),
            HistoricalPlayer(name: "Max Osgood", detailedPosition: .leftWing, age: 21, rating: 68),
            HistoricalPlayer(name: "Jermaine Idrissi", detailedPosition: .rightWing, age: 25, rating: 68),
            HistoricalPlayer(name: "Luciano Vasconcelos", detailedPosition: .striker, age: 27, rating: 71),
            HistoricalPlayer(name: "Billy Truscott", detailedPosition: .striker, age: 23, rating: 68),
            HistoricalPlayer(name: "Robert Whitfield", detailedPosition: .striker, age: 29, rating: 66),
            HistoricalPlayer(name: "Tom Ndiaye", detailedPosition: .centreBack, age: 20, rating: 63),
            HistoricalPlayer(name: "Sam Calloway", detailedPosition: .rightBack, age: 20, rating: 62),
            HistoricalPlayer(name: "Kyle Girard", detailedPosition: .centralMid, age: 19, rating: 61),
        ],
        "Portman Rovers": [
            HistoricalPlayer(name: "Marton Fenshaw", detailedPosition: .goalkeeper, age: 29, rating: 68),
            HistoricalPlayer(name: "Alex Osborne", detailedPosition: .goalkeeper, age: 24, rating: 60),
            HistoricalPlayer(name: "Carlos Redfern", detailedPosition: .rightBack, age: 26, rating: 67),
            HistoricalPlayer(name: "Damien Calder", detailedPosition: .centreBack, age: 28, rating: 68),
            HistoricalPlayer(name: "Gareth Marshall", detailedPosition: .centreBack, age: 25, rating: 67),
            HistoricalPlayer(name: "Tommy Ashcroft", detailedPosition: .leftBack, age: 24, rating: 66),
            HistoricalPlayer(name: "Jack Grantham", detailedPosition: .holding, age: 23, rating: 67),
            HistoricalPlayer(name: "Owen Bishop", detailedPosition: .centralMid, age: 22, rating: 66),
            HistoricalPlayer(name: "Lee Latham", detailedPosition: .attackingMid, age: 27, rating: 68),
            HistoricalPlayer(name: "Jon Foy", detailedPosition: .centralMid, age: 25, rating: 66),
            HistoricalPlayer(name: "Grant Prentice", detailedPosition: .rightWing, age: 24, rating: 67),
            HistoricalPlayer(name: "David Osgood", detailedPosition: .leftWing, age: 26, rating: 66),
            HistoricalPlayer(name: "Connor Idrissi", detailedPosition: .striker, age: 22, rating: 68),
            HistoricalPlayer(name: "Michael Vasconcelos", detailedPosition: .striker, age: 28, rating: 69),
            HistoricalPlayer(name: "Alan Truscott", detailedPosition: .striker, age: 30, rating: 65),
            HistoricalPlayer(name: "Josh Ndiaye", detailedPosition: .centreBack, age: 19, rating: 61),
            HistoricalPlayer(name: "Ben Calloway", detailedPosition: .rightBack, age: 21, rating: 61),
            HistoricalPlayer(name: "Tyler Girard", detailedPosition: .centralMid, age: 20, rating: 60),
        ],
        "Stamford Blues": [
            HistoricalPlayer(name: "Petr Novotny", detailedPosition: .goalkeeper, age: 28, rating: 87),
            HistoricalPlayer(name: "Ross Fenshaw", detailedPosition: .goalkeeper, age: 24, rating: 66),
            HistoricalPlayer(name: "Branislav Kral", detailedPosition: .rightBack, age: 26, rating: 82, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "John Radley", detailedPosition: .centreBack, age: 29, rating: 88, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Alex Devereux", detailedPosition: .centreBack, age: 28, rating: 79),
            HistoricalPlayer(name: "Ashley Corrigan", detailedPosition: .leftBack, age: 29, rating: 82, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .rightBack, age: 27, rating: 76),
            HistoricalPlayer(name: "Michael Owusu", detailedPosition: .holding, age: 27, rating: 84, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "John Obidi", detailedPosition: .holding, age: 23, rating: 78, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Frank Osgood", detailedPosition: .centralMid, age: 32, rating: 87, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Florent Girard", detailedPosition: .leftWing, age: 30, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ramires Nascimento", detailedPosition: .centralMid, age: 23, rating: 76),
            HistoricalPlayer(name: "Didier Marotta", detailedPosition: .striker, age: 32, rating: 89),
            HistoricalPlayer(name: "Nicolas Bertrand", detailedPosition: .striker, age: 31, rating: 82),
            HistoricalPlayer(name: "Salomon Beheton", detailedPosition: .striker, age: 25, rating: 74, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Yuri Orlov", detailedPosition: .leftWing, age: 26, rating: 72),
            HistoricalPlayer(name: "Paulo Salgueiro", detailedPosition: .rightBack, age: 31, rating: 70),
            HistoricalPlayer(name: "Josh Prewitt", detailedPosition: .centralMid, age: 20, rating: 68),
        ],
        "Wearside": [
            HistoricalPlayer(name: "Craig Halvorsen", detailedPosition: .goalkeeper, age: 27, rating: 76),
            HistoricalPlayer(name: "Marton Fenwick", detailedPosition: .goalkeeper, age: 23, rating: 62),
            HistoricalPlayer(name: "Nedum Okafor", detailedPosition: .centreBack, age: 29, rating: 74),
            HistoricalPlayer(name: "Michael Blackwood", detailedPosition: .centreBack, age: 26, rating: 75),
            HistoricalPlayer(name: "John Adeyemi", detailedPosition: .centreBack, age: 28, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Kieran Redfern", detailedPosition: .leftBack, age: 24, rating: 71),
            HistoricalPlayer(name: "Phil Bishop", detailedPosition: .rightBack, age: 25, rating: 70),
            HistoricalPlayer(name: "Lee Ward", detailedPosition: .holding, age: 22, rating: 74, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Jordan Prentice", detailedPosition: .centralMid, age: 20, rating: 73, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "David Calloway", detailedPosition: .centralMid, age: 28, rating: 70),
            HistoricalPlayer(name: "Steed Girard", detailedPosition: .attackingMid, age: 30, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ahmed Hassan", detailedPosition: .rightWing, age: 22, rating: 71),
            HistoricalPlayer(name: "Asamoah Mensah", detailedPosition: .striker, age: 24, rating: 82),
            HistoricalPlayer(name: "Darren Aldous", detailedPosition: .striker, age: 26, rating: 70, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Danny Foulkes", detailedPosition: .striker, age: 20, rating: 71, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Fraizer Latham", detailedPosition: .attackingMid, age: 21, rating: 68),
            HistoricalPlayer(name: "Titus Diallo", detailedPosition: .centreBack, age: 32, rating: 66),
            HistoricalPlayer(name: "Anton Grantham", detailedPosition: .holding, age: 25, rating: 65),
        ],
        "Aston Rovers": [
            HistoricalPlayer(name: "Brad Halvorsen", detailedPosition: .goalkeeper, age: 39, rating: 78),
            HistoricalPlayer(name: "Shay Osborne", detailedPosition: .goalkeeper, age: 25, rating: 62),
            HistoricalPlayer(name: "Alan Redfern", detailedPosition: .rightBack, age: 25, rating: 73),
            HistoricalPlayer(name: "Richard Aldous", detailedPosition: .centreBack, age: 30, rating: 79),
            HistoricalPlayer(name: "James Marshall", detailedPosition: .centreBack, age: 26, rating: 76),
            HistoricalPlayer(name: "Stephen Blackwood", detailedPosition: .leftBack, age: 28, rating: 74),
            HistoricalPlayer(name: "Ciaran Foulkes", detailedPosition: .centreBack, age: 20, rating: 68, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Fabian Prentice", detailedPosition: .centralMid, age: 20, rating: 72),
            HistoricalPlayer(name: "Stiliyan Ivanov", detailedPosition: .centralMid, age: 31, rating: 80, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Nigel Osgood", detailedPosition: .holding, age: 26, rating: 71),
            HistoricalPlayer(name: "Stewart Calloway", detailedPosition: .leftWing, age: 25, rating: 79, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ashley Aldous", detailedPosition: .rightWing, age: 25, rating: 84, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Gabriel Osei", detailedPosition: .striker, age: 24, rating: 79, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Emile Foy", detailedPosition: .striker, age: 32, rating: 74),
            HistoricalPlayer(name: "John Halvorsen", detailedPosition: .striker, age: 31, rating: 76),
            HistoricalPlayer(name: "Marc Albrighton", detailedPosition: .rightWing, age: 20, rating: 68),
            HistoricalPlayer(name: "Barry Prentice", detailedPosition: .attackingMid, age: 20, rating: 67),
            HistoricalPlayer(name: "Nathan Osei", detailedPosition: .striker, age: 19, rating: 66),
        ],
        "Valley Rovers": [
            HistoricalPlayer(name: "Rob Halvorsen", detailedPosition: .goalkeeper, age: 24, rating: 68),
            HistoricalPlayer(name: "Ben Fenshaw", detailedPosition: .goalkeeper, age: 22, rating: 61),
            HistoricalPlayer(name: "Chris Redfern", detailedPosition: .rightBack, age: 20, rating: 66),
            HistoricalPlayer(name: "Miguel Salgueiro", detailedPosition: .centreBack, age: 30, rating: 69),
            HistoricalPlayer(name: "Grant Bishop", detailedPosition: .centralMid, age: 31, rating: 68, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Darren Osgood", detailedPosition: .attackingMid, age: 27, rating: 71),
            HistoricalPlayer(name: "Kelly Devereux", detailedPosition: .leftBack, age: 24, rating: 66),
            HistoricalPlayer(name: "Gary Calder", detailedPosition: .centreBack, age: 32, rating: 68, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .holding, age: 26, rating: 67),
            HistoricalPlayer(name: "Nicky Grantham", detailedPosition: .centralMid, age: 26, rating: 68),
            HistoricalPlayer(name: "Chris Ashcroft", detailedPosition: .striker, age: 24, rating: 67),
            HistoricalPlayer(name: "Kyle Prentice", detailedPosition: .striker, age: 22, rating: 65),
            HistoricalPlayer(name: "Jonathan Marshall", detailedPosition: .centreBack, age: 30, rating: 65),
            HistoricalPlayer(name: "Bradley Latham", detailedPosition: .centralMid, age: 24, rating: 65),
            HistoricalPlayer(name: "Leon Foy", detailedPosition: .striker, age: 24, rating: 68),
            HistoricalPlayer(name: "Scott Wagstaff", detailedPosition: .rightWing, age: 19, rating: 63),
            HistoricalPlayer(name: "Josh Bishop", detailedPosition: .leftWing, age: 25, rating: 64),
            HistoricalPlayer(name: "Rob Calloway", detailedPosition: .striker, age: 29, rating: 66),
        ],
        "Solent": [
            HistoricalPlayer(name: "Kelvin Osborne", detailedPosition: .goalkeeper, age: 32, rating: 69),
            HistoricalPlayer(name: "Bartosz Bialkowski", detailedPosition: .goalkeeper, age: 23, rating: 62),
            HistoricalPlayer(name: "Danny Redfern", detailedPosition: .rightBack, age: 30, rating: 68),
            HistoricalPlayer(name: "Dan Ashdown", detailedPosition: .leftBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .centreBack, age: 26, rating: 71),
            HistoricalPlayer(name: "Jason Foulkes", detailedPosition: .centreBack, age: 22, rating: 67),
            HistoricalPlayer(name: "Jonathan Grantham", detailedPosition: .striker, age: 25, rating: 67),
            HistoricalPlayer(name: "Adam Kral", detailedPosition: .attackingMid, age: 22, rating: 74, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Morgan Girard", detailedPosition: .holding, age: 20, rating: 71),
            HistoricalPlayer(name: "Jos Bergman", detailedPosition: .centreBack, age: 27, rating: 68),
            HistoricalPlayer(name: "Papa Ndiaye", detailedPosition: .striker, age: 23, rating: 66),
            HistoricalPlayer(name: "Rickie Ashcroft", detailedPosition: .striker, age: 28, rating: 72),
            HistoricalPlayer(name: "David Fenwick", detailedPosition: .striker, age: 28, rating: 68),
            HistoricalPlayer(name: "Lee Calder", detailedPosition: .striker, age: 27, rating: 66),
            HistoricalPlayer(name: "Jason Blackwood", detailedPosition: .centralMid, age: 26, rating: 64),
            HistoricalPlayer(name: "Guly Salgueiro", detailedPosition: .rightWing, age: 23, rating: 65),
            HistoricalPlayer(name: "Radhi Hassan", detailedPosition: .centreBack, age: 34, rating: 64),
            HistoricalPlayer(name: "Dean Prentice", detailedPosition: .centralMid, age: 27, rating: 65),
        ],
        "Tyneside": [
            HistoricalPlayer(name: "Tim Novak", detailedPosition: .goalkeeper, age: 22, rating: 74),
            HistoricalPlayer(name: "Steve Fenshaw", detailedPosition: .goalkeeper, age: 35, rating: 72),
            HistoricalPlayer(name: "Danny Redfern", detailedPosition: .rightBack, age: 23, rating: 70),
            HistoricalPlayer(name: "Fabricio Salaberri", detailedPosition: .centreBack, age: 28, rating: 79),
            HistoricalPlayer(name: "Steven Ward", detailedPosition: .centreBack, age: 24, rating: 73),
            HistoricalPlayer(name: "Jose Alvarenga", detailedPosition: .leftBack, age: 24, rating: 76),
            HistoricalPlayer(name: "Cheick Diallo", detailedPosition: .holding, age: 24, rating: 78),
            HistoricalPlayer(name: "Joey Osgood", detailedPosition: .centralMid, age: 28, rating: 76, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Kevin Whitfield", detailedPosition: .centralMid, age: 28, rating: 77),
            HistoricalPlayer(name: "Hatem Idrissi", detailedPosition: .attackingMid, age: 23, rating: 79, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Jonas Bergman", detailedPosition: .rightWing, age: 27, rating: 73),
            HistoricalPlayer(name: "Andy Fenner", detailedPosition: .striker, age: 21, rating: 83),
            HistoricalPlayer(name: "Leon Truscott", detailedPosition: .striker, age: 22, rating: 68),
            HistoricalPlayer(name: "Shola Chastain", detailedPosition: .striker, age: 28, rating: 71),
            HistoricalPlayer(name: "Peter Nystrom", detailedPosition: .leftWing, age: 31, rating: 68),
            HistoricalPlayer(name: "James Osborne", detailedPosition: .rightBack, age: 25, rating: 65),
            HistoricalPlayer(name: "Alan Truscott", detailedPosition: .striker, age: 29, rating: 68, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Sanchez Foulkes", detailedPosition: .leftWing, age: 19, rating: 63),
        ],
        "White Hart Athletic": [
            HistoricalPlayer(name: "Heurelho Nascimento", detailedPosition: .goalkeeper, age: 30, rating: 78),
            HistoricalPlayer(name: "Carlo Serrano", detailedPosition: .goalkeeper, age: 37, rating: 68),
            HistoricalPlayer(name: "Vedran Novak", detailedPosition: .rightBack, age: 25, rating: 77),
            HistoricalPlayer(name: "Michael Truscott", detailedPosition: .centreBack, age: 27, rating: 80),
            HistoricalPlayer(name: "Ledley Ashcroft", detailedPosition: .centreBack, age: 30, rating: 82),
            HistoricalPlayer(name: "Benoit Diallo", detailedPosition: .leftBack, age: 26, rating: 76),
            HistoricalPlayer(name: "Younes Idrissi", detailedPosition: .centreBack, age: 24, rating: 73),
            HistoricalPlayer(name: "Gareth Baile", detailedPosition: .leftWing, age: 21, rating: 92, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Luka Kral", detailedPosition: .attackingMid, age: 25, rating: 87, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Rafael Doren", detailedPosition: .attackingMid, age: 27, rating: 83, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Wilson Aráoz", detailedPosition: .holding, age: 26, rating: 75),
            HistoricalPlayer(name: "Aaron Prescott", detailedPosition: .rightWing, age: 23, rating: 79),
            HistoricalPlayer(name: "Peter Foy", detailedPosition: .striker, age: 29, rating: 78),
            HistoricalPlayer(name: "Jermain Prescott", detailedPosition: .striker, age: 28, rating: 76),
            HistoricalPlayer(name: "Roman Orlov", detailedPosition: .striker, age: 28, rating: 72),
            HistoricalPlayer(name: "Tom Latham", detailedPosition: .centralMid, age: 23, rating: 75, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Niko Novak", detailedPosition: .attackingMid, age: 25, rating: 74),
            HistoricalPlayer(name: "Sandro Nascimento", detailedPosition: .holding, age: 21, rating: 70),
        ],
        "Filbert Foxes": [
            HistoricalPlayer(name: "Chris Fenshaw", detailedPosition: .goalkeeper, age: 27, rating: 65),
            HistoricalPlayer(name: "Kasper Larsen", detailedPosition: .goalkeeper, age: 23, rating: 68),
            HistoricalPlayer(name: "Jack Redfern", detailedPosition: .centreBack, age: 24, rating: 66),
            HistoricalPlayer(name: "Sol Camwell", detailedPosition: .centreBack, age: 35, rating: 74, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Wes Truscott", detailedPosition: .leftBack, age: 30, rating: 68),
            HistoricalPlayer(name: "Bruno Salgueiro", detailedPosition: .leftBack, age: 32, rating: 65),
            HistoricalPlayer(name: "Andy Ashcroft", detailedPosition: .centralMid, age: 21, rating: 68),
            HistoricalPlayer(name: "Richie Grantham", detailedPosition: .centralMid, age: 29, rating: 67),
            HistoricalPlayer(name: "Neil Bishop", detailedPosition: .attackingMid, age: 26, rating: 67),
            HistoricalPlayer(name: "Lloyd Osgood", detailedPosition: .leftWing, age: 27, rating: 68),
            HistoricalPlayer(name: "Jermaine Whitlock", detailedPosition: .striker, age: 26, rating: 71),
            HistoricalPlayer(name: "Steve Marshall", detailedPosition: .striker, age: 34, rating: 66),
            HistoricalPlayer(name: "Paul Calloway", detailedPosition: .attackingMid, age: 25, rating: 65),
            HistoricalPlayer(name: "Matt Prentice", detailedPosition: .striker, age: 24, rating: 68),
            HistoricalPlayer(name: "Michael Foy", detailedPosition: .centreBack, age: 22, rating: 64),
            HistoricalPlayer(name: "Aleksandar Tunchev", detailedPosition: .rightBack, age: 28, rating: 63),
            HistoricalPlayer(name: "Sean Aldous", detailedPosition: .centreBack, age: 25, rating: 64),
            HistoricalPlayer(name: "Max Idrissi", detailedPosition: .rightWing, age: 22, rating: 66),
        ],
        "Teesside": [
            HistoricalPlayer(name: "Jason Fenshaw", detailedPosition: .goalkeeper, age: 20, rating: 63),
            HistoricalPlayer(name: "Ross Redfern", detailedPosition: .goalkeeper, age: 25, rating: 65),
            HistoricalPlayer(name: "Justin Ashcroft", detailedPosition: .rightBack, age: 25, rating: 66),
            HistoricalPlayer(name: "Matthew Calder", detailedPosition: .centreBack, age: 24, rating: 65),
            HistoricalPlayer(name: "Rhys Marshall", detailedPosition: .centreBack, age: 21, rating: 64),
            HistoricalPlayer(name: "Andrew Osgood", detailedPosition: .leftBack, age: 24, rating: 66),
            HistoricalPlayer(name: "Barry Grantham", detailedPosition: .centralMid, age: 31, rating: 68),
            HistoricalPlayer(name: "Adam Latham", detailedPosition: .rightWing, age: 22, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Gary Foy", detailedPosition: .centralMid, age: 27, rating: 67),
            HistoricalPlayer(name: "Kris Prentice", detailedPosition: .striker, age: 26, rating: 69),
            HistoricalPlayer(name: "Scott Bishop", detailedPosition: .striker, age: 26, rating: 68),
            HistoricalPlayer(name: "Tarmo Larsen", detailedPosition: .striker, age: 23, rating: 62),
            HistoricalPlayer(name: "Faris Idrissi", detailedPosition: .holding, age: 22, rating: 63),
            HistoricalPlayer(name: "Joe Calloway", detailedPosition: .leftBack, age: 19, rating: 62),
            HistoricalPlayer(name: "Julio Salgueiro", detailedPosition: .leftWing, age: 30, rating: 65),
            HistoricalPlayer(name: "Willo Ashdown", detailedPosition: .attackingMid, age: 24, rating: 62),
            HistoricalPlayer(name: "David Grantham", detailedPosition: .centreBack, age: 25, rating: 65),
            HistoricalPlayer(name: "Marvin Vasconcelos", detailedPosition: .striker, age: 22, rating: 65),
        ],
        "Upton Athletic": [
            HistoricalPlayer(name: "Rob Osborne", detailedPosition: .goalkeeper, age: 30, rating: 78),
            HistoricalPlayer(name: "Manuel Salaberri", detailedPosition: .goalkeeper, age: 33, rating: 70),
            HistoricalPlayer(name: "Herita Ndiaye", detailedPosition: .leftBack, age: 27, rating: 68),
            HistoricalPlayer(name: "Danny Truscott", detailedPosition: .centreBack, age: 30, rating: 71),
            HistoricalPlayer(name: "James Marshall", detailedPosition: .centreBack, age: 21, rating: 68),
            HistoricalPlayer(name: "Guy Idrissi", detailedPosition: .rightBack, age: 28, rating: 69),
            HistoricalPlayer(name: "Scott Foy", detailedPosition: .holding, age: 30, rating: 82, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mark Latham", detailedPosition: .centralMid, age: 23, rating: 75),
            HistoricalPlayer(name: "Kieron Prewitt", detailedPosition: .attackingMid, age: 31, rating: 68, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Valon Novak", detailedPosition: .centralMid, age: 25, rating: 70),
            HistoricalPlayer(name: "Victor Osei", detailedPosition: .leftWing, age: 22, rating: 72, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Frederic Girard", detailedPosition: .striker, age: 32, rating: 68),
            HistoricalPlayer(name: "Carlton Whitfield", detailedPosition: .striker, age: 27, rating: 73),
            HistoricalPlayer(name: "Demba Mensah", detailedPosition: .striker, age: 25, rating: 76),
            HistoricalPlayer(name: "Zavon Foulkes", detailedPosition: .rightWing, age: 22, rating: 64),
            HistoricalPlayer(name: "Radoslav Ivanov", detailedPosition: .holding, age: 29, rating: 64),
            HistoricalPlayer(name: "Wayne Fenner", detailedPosition: .leftBack, age: 30, rating: 68),
            HistoricalPlayer(name: "Jack Bishop", detailedPosition: .centralMid, age: 21, rating: 65),
        ],
        "Goodison Blues": [
            HistoricalPlayer(name: "Tim Truscott", detailedPosition: .goalkeeper, age: 31, rating: 82),
            HistoricalPlayer(name: "Jan Novak", detailedPosition: .goalkeeper, age: 26, rating: 63),
            HistoricalPlayer(name: "Tony Ashcroft", detailedPosition: .rightBack, age: 29, rating: 71),
            HistoricalPlayer(name: "Phil Latham", detailedPosition: .centreBack, age: 28, rating: 79),
            HistoricalPlayer(name: "Sylvain Girard", detailedPosition: .centreBack, age: 32, rating: 77),
            HistoricalPlayer(name: "Leighton Calder", detailedPosition: .leftBack, age: 25, rating: 81),
            HistoricalPlayer(name: "Phil Osgood", detailedPosition: .centreBack, age: 33, rating: 73, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Marouane Amrani", detailedPosition: .attackingMid, age: 22, rating: 79, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Mikel Puig", detailedPosition: .attackingMid, age: 28, rating: 84, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Leon Foy", detailedPosition: .centralMid, age: 29, rating: 74),
            HistoricalPlayer(name: "Steven Botha", detailedPosition: .leftWing, age: 28, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Diniyar Orlov", detailedPosition: .rightWing, age: 26, rating: 72),
            HistoricalPlayer(name: "Tim Prentice", detailedPosition: .attackingMid, age: 30, rating: 79, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Yakubu Osei", detailedPosition: .striker, age: 27, rating: 76),
            HistoricalPlayer(name: "Louis Girard", detailedPosition: .striker, age: 31, rating: 76),
            HistoricalPlayer(name: "Jack Latham", detailedPosition: .centralMid, age: 19, rating: 70),
            HistoricalPlayer(name: "Seamus Foy", detailedPosition: .rightBack, age: 21, rating: 68),
            HistoricalPlayer(name: "Jermaine Truscott", detailedPosition: .striker, age: 27, rating: 68),
        ],
        "Pride Rams": [
            HistoricalPlayer(name: "Stephen Fenshaw", detailedPosition: .goalkeeper, age: 27, rating: 65),
            HistoricalPlayer(name: "Saul Redfern", detailedPosition: .goalkeeper, age: 24, rating: 60),
            HistoricalPlayer(name: "Miles Ashcroft", detailedPosition: .centreBack, age: 20, rating: 64),
            HistoricalPlayer(name: "Jason Calder", detailedPosition: .centreBack, age: 25, rating: 65),
            HistoricalPlayer(name: "Shaun Marshall", detailedPosition: .rightBack, age: 26, rating: 66),
            HistoricalPlayer(name: "Stephen Grantham", detailedPosition: .centralMid, age: 27, rating: 65),
            HistoricalPlayer(name: "Kris Bishop", detailedPosition: .leftWing, age: 27, rating: 69, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Nathan Osgood", detailedPosition: .striker, age: 28, rating: 64),
            HistoricalPlayer(name: "Robbie Latham", detailedPosition: .centralMid, age: 35, rating: 64),
            HistoricalPlayer(name: "Rob Foy", detailedPosition: .striker, age: 30, rating: 65),
            HistoricalPlayer(name: "John Prentice", detailedPosition: .rightBack, age: 21, rating: 62),
            HistoricalPlayer(name: "Chris Grantham", detailedPosition: .centreBack, age: 29, rating: 63),
            HistoricalPlayer(name: "Gareth Idrissi", detailedPosition: .leftBack, age: 32, rating: 62),
            HistoricalPlayer(name: "Ben Foulkes", detailedPosition: .attackingMid, age: 21, rating: 62),
            HistoricalPlayer(name: "Theo Vasconcelos", detailedPosition: .striker, age: 20, rating: 63),
            HistoricalPlayer(name: "Przemyslaw Kazimierczak", detailedPosition: .goalkeeper, age: 24, rating: 60),
            HistoricalPlayer(name: "Jake Osborne", detailedPosition: .centreBack, age: 26, rating: 62),
            HistoricalPlayer(name: "Conor Ndiaye", detailedPosition: .striker, age: 22, rating: 61),
        ],
        "Etihad Blues": [
            HistoricalPlayer(name: "Joe Ashdown", detailedPosition: .goalkeeper, age: 23, rating: 83),
            HistoricalPlayer(name: "Shay Truscott", detailedPosition: .goalkeeper, age: 34, rating: 78),
            HistoricalPlayer(name: "Pablo Cerezo", detailedPosition: .rightBack, age: 25, rating: 78),
            HistoricalPlayer(name: "Vincent Amara", detailedPosition: .centreBack, age: 24, rating: 86),
            HistoricalPlayer(name: "Joleon Ashcroft", detailedPosition: .centreBack, age: 27, rating: 78),
            HistoricalPlayer(name: "Aleksandar Ivanov", detailedPosition: .leftBack, age: 24, rating: 76),
            HistoricalPlayer(name: "Micah Calder", detailedPosition: .rightBack, age: 22, rating: 74, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Kolo Diallo", detailedPosition: .centreBack, age: 29, rating: 79),
            HistoricalPlayer(name: "Nigel Bergman", detailedPosition: .holding, age: 25, rating: 79),
            HistoricalPlayer(name: "Gareth Osgood", detailedPosition: .holding, age: 29, rating: 80, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "David Puig", detailedPosition: .attackingMid, age: 24, rating: 87, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Carlos Marotta", detailedPosition: .striker, age: 26, rating: 89, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Mario Rinaldi", detailedPosition: .striker, age: 20, rating: 80),
            HistoricalPlayer(name: "Emmanuel Diallo", detailedPosition: .striker, age: 26, rating: 78),
            HistoricalPlayer(name: "James Truscott", detailedPosition: .rightWing, age: 24, rating: 78, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Adam Foy", detailedPosition: .leftWing, age: 23, rating: 74),
            HistoricalPlayer(name: "Patrick Amara", detailedPosition: .holding, age: 34, rating: 72, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Edin Kral", detailedPosition: .striker, age: 24, rating: 82),
        ],
        "Highfield Athletic": [
            HistoricalPlayer(name: "Keiren Osborne", detailedPosition: .goalkeeper, age: 25, rating: 65),
            HistoricalPlayer(name: "Chris Fenshaw", detailedPosition: .goalkeeper, age: 22, rating: 60),
            HistoricalPlayer(name: "Stephen Ashcroft", detailedPosition: .rightBack, age: 30, rating: 63),
            HistoricalPlayer(name: "Elliott Calder", detailedPosition: .centreBack, age: 26, rating: 64),
            HistoricalPlayer(name: "Sammy Grantham", detailedPosition: .centralMid, age: 26, rating: 65),
            HistoricalPlayer(name: "Gary Bishop", detailedPosition: .holding, age: 22, rating: 63),
            HistoricalPlayer(name: "Carl Latham", detailedPosition: .attackingMid, age: 27, rating: 66),
            HistoricalPlayer(name: "Freddy Prentice", detailedPosition: .striker, age: 26, rating: 65),
            HistoricalPlayer(name: "Clive Foy", detailedPosition: .striker, age: 29, rating: 63),
            HistoricalPlayer(name: "Michael Idrissi", detailedPosition: .leftWing, age: 28, rating: 64),
            HistoricalPlayer(name: "David Osgood", detailedPosition: .centralMid, age: 25, rating: 63),
            HistoricalPlayer(name: "Marlon Truscott", detailedPosition: .striker, age: 29, rating: 66),
            HistoricalPlayer(name: "Charlie Vasconcelos", detailedPosition: .centralMid, age: 24, rating: 61),
            HistoricalPlayer(name: "Lee Fenshaw", detailedPosition: .goalkeeper, age: 26, rating: 62),
            HistoricalPlayer(name: "Cyrus Foulkes", detailedPosition: .rightBack, age: 18, rating: 58),
            HistoricalPlayer(name: "Jermaine Ndiaye", detailedPosition: .centreBack, age: 27, rating: 61),
            HistoricalPlayer(name: "Franck Girard", detailedPosition: .leftWing, age: 21, rating: 61),
            HistoricalPlayer(name: "Gavin Calloway", detailedPosition: .centreBack, age: 20, rating: 59),
        ],
        "Valley Parade": [
            HistoricalPlayer(name: "Simon Osborne", detailedPosition: .goalkeeper, age: 20, rating: 60),
            HistoricalPlayer(name: "Jon Fenshaw", detailedPosition: .goalkeeper, age: 22, rating: 61),
            HistoricalPlayer(name: "Luke Ashcroft", detailedPosition: .centreBack, age: 25, rating: 61),
            HistoricalPlayer(name: "Zesh Idrissi", detailedPosition: .centreBack, age: 27, rating: 62),
            HistoricalPlayer(name: "Steve Calder", detailedPosition: .rightBack, age: 33, rating: 60),
            HistoricalPlayer(name: "Michael Grantham", detailedPosition: .centralMid, age: 30, rating: 62),
            HistoricalPlayer(name: "Lee Latham", detailedPosition: .holding, age: 28, rating: 61),
            HistoricalPlayer(name: "Gareth Prentice", detailedPosition: .rightWing, age: 22, rating: 62),
            HistoricalPlayer(name: "James Foy", detailedPosition: .striker, age: 22, rating: 62),
            HistoricalPlayer(name: "Peter Vasconcelos", detailedPosition: .striker, age: 34, rating: 60),
            HistoricalPlayer(name: "Michael Osgood", detailedPosition: .striker, age: 30, rating: 59),
            HistoricalPlayer(name: "Robbie Truscott", detailedPosition: .leftBack, age: 20, rating: 58),
            HistoricalPlayer(name: "Tom Ndiaye", detailedPosition: .holding, age: 18, rating: 57),
            HistoricalPlayer(name: "Scott Fenshaw", detailedPosition: .goalkeeper, age: 22, rating: 58),
            HistoricalPlayer(name: "Louis Girard", detailedPosition: .striker, age: 18, rating: 56),
            HistoricalPlayer(name: "Craig Bishop", detailedPosition: .centralMid, age: 23, rating: 61),
            HistoricalPlayer(name: "Omar Idrissi", detailedPosition: .leftWing, age: 27, rating: 60),
            HistoricalPlayer(name: "Kyel Foulkes", detailedPosition: .leftWing, age: 21, rating: 60),
        ],
    ]
}
