//
//  HistoricalSquads2000.swift
//  Retro Season Manager
//
//  Real first-team squads for the 20 clubs of the actual 2000/01 FA
//  First Division season, as they stood at the start of that season.
//  Ratings and detailed positions are a game-balance approximation of each
//  player's real-world stature and role that year, not a precise
//  historical statistic. Sourced from club season records; a handful of
//  squad/fringe entries for the less-documented clubs are best-effort.
//

import Foundation

/// One real player slot used to seed a club's opening-day squad.
struct HistoricalPlayer {
    let name: String
    let detailedPosition: DetailedPosition
    let age: Int
    let rating: Int
    let secondaryPositions: [DetailedPosition]

    init(name: String, detailedPosition: DetailedPosition, age: Int, rating: Int,
         secondaryPositions: [DetailedPosition] = []) {
        self.name = name
        self.detailedPosition = detailedPosition
        self.age = age
        self.rating = rating
        self.secondaryPositions = secondaryPositions
    }
}

/// Real 2000/01 First Division rosters, keyed by the club name used in
/// `GameStore.tierPools`. Each squad is 18 players: 2 GK, 6 DEF, 6 MID, 4 FWD.
enum HistoricalSquads2000 {
    static let squads: [String: [HistoricalPlayer]] = [
        "Old Trafford Reds": [
            HistoricalPlayer(name: "Mathis Harding", detailedPosition: .goalkeeper, age: 29, rating: 88),
            HistoricalPlayer(name: "Stefano Castellan", detailedPosition: .goalkeeper, age: 37, rating: 58),
            HistoricalPlayer(name: "Carlos Mendes", detailedPosition: .rightBack, age: 25, rating: 83),
            HistoricalPlayer(name: "Ian Castellan", detailedPosition: .centreBack, age: 28, rating: 89),
            HistoricalPlayer(name: "Kian Diallo", detailedPosition: .leftBack, age: 34, rating: 74, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Craig Horvat", detailedPosition: .centreBack, age: 22, rating: 76, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Bjorn Radley", detailedPosition: .centreBack, age: 20, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Magnus Harding", detailedPosition: .leftBack, age: 23, rating: 74, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Roy Cahill", detailedPosition: .holding, age: 28, rating: 92, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "David Whitlock", detailedPosition: .rightWing, age: 25, rating: 90, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ryan Merrick", detailedPosition: .leftWing, age: 26, rating: 88),
            HistoricalPlayer(name: "Paul Kenwright", detailedPosition: .centralMid, age: 25, rating: 88, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Idris Fontaine", detailedPosition: .centralMid, age: 25, rating: 76, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Anton Whitfield", detailedPosition: .striker, age: 23, rating: 66, secondaryPositions: [.leftWing, .leftBack]),
            HistoricalPlayer(name: "Colin Vogel", detailedPosition: .striker, age: 28, rating: 84),
            HistoricalPlayer(name: "Youssef Sherrington", detailedPosition: .striker, age: 28, rating: 83, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Daniel Toure", detailedPosition: .attackingMid, age: 34, rating: 78, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Emil Dimitrov", detailedPosition: .striker, age: 27, rating: 80),
        ],
        "Highbury": [
            HistoricalPlayer(name: "Kyle Halvorsen", detailedPosition: .goalkeeper, age: 36, rating: 86),
            HistoricalPlayer(name: "Henrik Dimitrov", detailedPosition: .goalkeeper, age: 23, rating: 64),
            HistoricalPlayer(name: "Thomas Vasconcelos", detailedPosition: .centreBack, age: 33, rating: 85),
            HistoricalPlayer(name: "Emil Marsh", detailedPosition: .centreBack, age: 34, rating: 82),
            HistoricalPlayer(name: "Jonas Horvat", detailedPosition: .rightBack, age: 36, rating: 72),
            HistoricalPlayer(name: "Mark Krause", detailedPosition: .leftBack, age: 25, rating: 77),
            HistoricalPlayer(name: "Liam Winstanley", detailedPosition: .rightBack, age: 31, rating: 68, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Mateo Duarte", detailedPosition: .leftBack, age: 19, rating: 70),
            HistoricalPlayer(name: "Patrick Amara", detailedPosition: .holding, age: 24, rating: 89, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "James Rousseau", detailedPosition: .leftWing, age: 26, rating: 86, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Milan Mendes", detailedPosition: .attackingMid, age: 23, rating: 82, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Noah Almada", detailedPosition: .centralMid, age: 27, rating: 75, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Milan Blackwood", detailedPosition: .holding, age: 29, rating: 66, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Wesley Sarr", detailedPosition: .centralMid, age: 23, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Thierry Almeida", detailedPosition: .striker, age: 22, rating: 92, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Dennis Verhoeven", detailedPosition: .striker, age: 31, rating: 89, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Hector Hartmann", detailedPosition: .striker, age: 24, rating: 79, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Andre Sandham", detailedPosition: .striker, age: 26, rating: 78, secondaryPositions: [.leftWing]),
        ],
        "Mersey Reds": [
            HistoricalPlayer(name: "Kian Hartmann", detailedPosition: .goalkeeper, age: 25, rating: 77),
            HistoricalPlayer(name: "Emeka Horvat", detailedPosition: .goalkeeper, age: 27, rating: 58),
            HistoricalPlayer(name: "Erik Ashworth", detailedPosition: .centreBack, age: 25, rating: 76),
            HistoricalPlayer(name: "Mark Foulkes", detailedPosition: .rightBack, age: 27, rating: 78, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Karim Rousseau", detailedPosition: .centreBack, age: 26, rating: 84),
            HistoricalPlayer(name: "Jamie Rousell", detailedPosition: .rightBack, age: 22, rating: 78, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Tomas Osgood", detailedPosition: .leftBack, age: 28, rating: 77),
            HistoricalPlayer(name: "Yusuf Calder", detailedPosition: .rightBack, age: 25, rating: 64, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Steven Halloran", detailedPosition: .centralMid, age: 20, rating: 84, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Malick Camara", detailedPosition: .holding, age: 26, rating: 78),
            HistoricalPlayer(name: "Colin Wenzel", detailedPosition: .centralMid, age: 35, rating: 77),
            HistoricalPlayer(name: "Ian Toure", detailedPosition: .attackingMid, age: 26, rating: 74, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Marcus Eriksson", detailedPosition: .centralMid, age: 23, rating: 72, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Nathan Sherrington", detailedPosition: .striker, age: 26, rating: 72, secondaryPositions: [.leftWing, .attackingMid]),
            HistoricalPlayer(name: "Michael Prescott", detailedPosition: .striker, age: 20, rating: 89),
            HistoricalPlayer(name: "Robbie Sandham", detailedPosition: .striker, age: 25, rating: 83),
            HistoricalPlayer(name: "Henrik Okafor", detailedPosition: .striker, age: 22, rating: 78, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Rasmus Winstanley", detailedPosition: .attackingMid, age: 29, rating: 74, secondaryPositions: [.striker]),
        ],
        "Elland Athletic": [
            HistoricalPlayer(name: "Viktor Salgueiro", detailedPosition: .goalkeeper, age: 33, rating: 85),
            HistoricalPlayer(name: "Julio Fenwick", detailedPosition: .goalkeeper, age: 20, rating: 62),
            HistoricalPlayer(name: "Karim Toure", detailedPosition: .rightBack, age: 26, rating: 73),
            HistoricalPlayer(name: "Callum Radley", detailedPosition: .leftBack, age: 22, rating: 76),
            HistoricalPlayer(name: "Thomas Ashworth", detailedPosition: .centreBack, age: 20, rating: 81),
            HistoricalPlayer(name: "Viktor Redfern", detailedPosition: .centreBack, age: 26, rating: 75, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Erik Keita", detailedPosition: .centreBack, age: 31, rating: 77, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Marcus Nystrom", detailedPosition: .centreBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Liam Hartmann", detailedPosition: .holding, age: 25, rating: 81, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Sven Salgueiro", detailedPosition: .centralMid, age: 23, rating: 81, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Dean Almada", detailedPosition: .holding, age: 31, rating: 77),
            HistoricalPlayer(name: "Ethan Keita", detailedPosition: .centralMid, age: 22, rating: 72),
            HistoricalPlayer(name: "Curtis Boateng", detailedPosition: .centralMid, age: 20, rating: 60),
            HistoricalPlayer(name: "Kian Prewitt", detailedPosition: .leftWing, age: 26, rating: 66),
            HistoricalPlayer(name: "Colin Bernard", detailedPosition: .striker, age: 24, rating: 84),
            HistoricalPlayer(name: "Craig Rousseau", detailedPosition: .striker, age: 21, rating: 84, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Emilio Fischer", detailedPosition: .striker, age: 21, rating: 73),
            HistoricalPlayer(name: "Pietro Ashcroft", detailedPosition: .striker, age: 19, rating: 68, secondaryPositions: [.rightWing]),
        ],
        "Portman Rovers": [
            HistoricalPlayer(name: "Yusuf Prentice", detailedPosition: .goalkeeper, age: 22, rating: 78),
            HistoricalPlayer(name: "Julio Reuter", detailedPosition: .goalkeeper, age: 34, rating: 56),
            HistoricalPlayer(name: "Nathan Berg", detailedPosition: .rightBack, age: 30, rating: 70),
            HistoricalPlayer(name: "Callum Girard", detailedPosition: .leftBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Karim Foulkes", detailedPosition: .centreBack, age: 27, rating: 69, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Steven Krause", detailedPosition: .centreBack, age: 26, rating: 77, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Magnus Salgueiro", detailedPosition: .centreBack, age: 19, rating: 62),
            HistoricalPlayer(name: "James Calder", detailedPosition: .centreBack, age: 32, rating: 56, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Ivan Bernard", detailedPosition: .centralMid, age: 31, rating: 75, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Jonas Prentice", detailedPosition: .holding, age: 26, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Ryan Duarte", detailedPosition: .leftWing, age: 24, rating: 68, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Emeka Redfern", detailedPosition: .centralMid, age: 23, rating: 66, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Pietro Vogel", detailedPosition: .leftWing, age: 25, rating: 68),
            HistoricalPlayer(name: "Liam Dimitrov", detailedPosition: .rightWing, age: 25, rating: 62, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Klaus Castellan", detailedPosition: .striker, age: 27, rating: 76),
            HistoricalPlayer(name: "Dario Brandt", detailedPosition: .striker, age: 24, rating: 68, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Rafael Toure", detailedPosition: .striker, age: 25, rating: 60),
            HistoricalPlayer(name: "Callum Osgood", detailedPosition: .striker, age: 20, rating: 50),
        ],
        "Stamford Blues": [
            HistoricalPlayer(name: "Gordon Marsh", detailedPosition: .goalkeeper, age: 33, rating: 81),
            HistoricalPlayer(name: "Gareth Mensah", detailedPosition: .goalkeeper, age: 26, rating: 68),
            HistoricalPlayer(name: "Emil Winstanley", detailedPosition: .centreBack, age: 31, rating: 85, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Kevin Prentice", detailedPosition: .centreBack, age: 32, rating: 80),
            HistoricalPlayer(name: "Jamie Brandt", detailedPosition: .leftBack, age: 31, rating: 77, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Bjorn Ivanov", detailedPosition: .leftBack, age: 21, rating: 72),
            HistoricalPlayer(name: "Nico Blackwood", detailedPosition: .rightBack, age: 21, rating: 68),
            HistoricalPlayer(name: "John Radley", detailedPosition: .centreBack, age: 19, rating: 72),
            HistoricalPlayer(name: "Scott Sandham", detailedPosition: .centralMid, age: 33, rating: 78, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Diego Prentice", detailedPosition: .centralMid, age: 30, rating: 79, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Luca Castellan", detailedPosition: .attackingMid, age: 32, rating: 80, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Andre Ashcroft", detailedPosition: .holding, age: 31, rating: 72, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Youssef Mendes", detailedPosition: .centralMid, age: 21, rating: 60),
            HistoricalPlayer(name: "Oskar Zeman", detailedPosition: .striker, age: 25, rating: 52, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Nico Lefevre", detailedPosition: .striker, age: 28, rating: 85),
            HistoricalPlayer(name: "Gianfranco Rialto", detailedPosition: .attackingMid, age: 34, rating: 86, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Sven Teixeira", detailedPosition: .striker, age: 21, rating: 74, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Adam Devereux", detailedPosition: .striker, age: 22, rating: 70, secondaryPositions: [.rightWing]),
        ],
        "Wearside": [
            HistoricalPlayer(name: "Karim Serrano", detailedPosition: .goalkeeper, age: 24, rating: 75),
            HistoricalPlayer(name: "Andre Boateng", detailedPosition: .goalkeeper, age: 29, rating: 56),
            HistoricalPlayer(name: "Diego Petrov", detailedPosition: .leftBack, age: 25, rating: 68),
            HistoricalPlayer(name: "Milan Sherrington", detailedPosition: .centreBack, age: 27, rating: 66),
            HistoricalPlayer(name: "Tariq Havel", detailedPosition: .centreBack, age: 25, rating: 65),
            HistoricalPlayer(name: "Rafael Ashworth", detailedPosition: .centreBack, age: 37, rating: 62),
            HistoricalPlayer(name: "Diego Karlsen", detailedPosition: .rightBack, age: 23, rating: 58, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Petr Prewitt", detailedPosition: .centreBack, age: 27, rating: 66),
            HistoricalPlayer(name: "Sven Camara", detailedPosition: .attackingMid, age: 29, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Leo Krause", detailedPosition: .leftWing, age: 23, rating: 70, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Carlos Vasconcelos", detailedPosition: .holding, age: 28, rating: 72, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Viktor Ndiaye", detailedPosition: .centralMid, age: 21, rating: 64, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Tomas Berg", detailedPosition: .centralMid, age: 31, rating: 62),
            HistoricalPlayer(name: "Emilio Serrano", detailedPosition: .holding, age: 33, rating: 64),
            HistoricalPlayer(name: "Yusuf Halvorsen", detailedPosition: .striker, age: 27, rating: 82),
            HistoricalPlayer(name: "Rafael Fischer", detailedPosition: .striker, age: 33, rating: 74),
            HistoricalPlayer(name: "Anton Dimitrov", detailedPosition: .striker, age: 25, rating: 58),
            HistoricalPlayer(name: "Scott Eriksson", detailedPosition: .striker, age: 25, rating: 50),
        ],
        "Aston Rovers": [
            HistoricalPlayer(name: "Connor Boateng", detailedPosition: .goalkeeper, age: 29, rating: 81),
            HistoricalPlayer(name: "Kofi Duarte", detailedPosition: .goalkeeper, age: 23, rating: 62),
            HistoricalPlayer(name: "Niklas Halvorsen", detailedPosition: .centreBack, age: 29, rating: 81, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Steven Zeman", detailedPosition: .centreBack, age: 27, rating: 78),
            HistoricalPlayer(name: "Gordon Harding", detailedPosition: .rightBack, age: 24, rating: 68),
            HistoricalPlayer(name: "Mateo Havel", detailedPosition: .leftBack, age: 28, rating: 66),
            HistoricalPlayer(name: "Nathan Salgueiro", detailedPosition: .leftBack, age: 31, rating: 72, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Felix Novak", detailedPosition: .leftBack, age: 19, rating: 70, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mark Serrano", detailedPosition: .attackingMid, age: 32, rating: 78, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Ryan Baumann", detailedPosition: .leftWing, age: 33, rating: 84, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Leo Boateng", detailedPosition: .holding, age: 24, rating: 72, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Callum Okafor", detailedPosition: .centralMid, age: 32, rating: 68),
            HistoricalPlayer(name: "Daniel Sandham", detailedPosition: .attackingMid, age: 23, rating: 70, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Emilio Reuter", detailedPosition: .striker, age: 28, rating: 64, secondaryPositions: [.rightWing, .centralMid]),
            HistoricalPlayer(name: "Henrik Reuter", detailedPosition: .striker, age: 31, rating: 78),
            HistoricalPlayer(name: "Stefano Adeyemi", detailedPosition: .striker, age: 24, rating: 72),
            HistoricalPlayer(name: "Youssef Dimitrov", detailedPosition: .attackingMid, age: 33, rating: 68, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Bjorn Adeyemi", detailedPosition: .striker, age: 25, rating: 62),
        ],
        "Valley Rovers": [
            HistoricalPlayer(name: "Erik Solheim", detailedPosition: .goalkeeper, age: 29, rating: 74),
            HistoricalPlayer(name: "Mateo Almada", detailedPosition: .goalkeeper, age: 28, rating: 56),
            HistoricalPlayer(name: "Jonas Calloway", detailedPosition: .leftBack, age: 28, rating: 66),
            HistoricalPlayer(name: "James Vogel", detailedPosition: .centreBack, age: 24, rating: 64),
            HistoricalPlayer(name: "Daniel Ivanov", detailedPosition: .rightBack, age: 26, rating: 62, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Oskar Karlsen", detailedPosition: .leftBack, age: 19, rating: 62),
            HistoricalPlayer(name: "Felipe Cahill", detailedPosition: .centreBack, age: 30, rating: 58),
            HistoricalPlayer(name: "Callum Prentice", detailedPosition: .centreBack, age: 26, rating: 62),
            HistoricalPlayer(name: "Felix Moreau", detailedPosition: .centralMid, age: 25, rating: 70, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Erik Horvat", detailedPosition: .attackingMid, age: 23, rating: 72, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Diego Latham", detailedPosition: .rightWing, age: 29, rating: 66, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Tomas Karlsen", detailedPosition: .rightWing, age: 24, rating: 62, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Petr Toure", detailedPosition: .holding, age: 19, rating: 68, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Tariq Grantham", detailedPosition: .leftWing, age: 28, rating: 58),
            HistoricalPlayer(name: "Felipe Blackwood", detailedPosition: .striker, age: 31, rating: 66),
            HistoricalPlayer(name: "Niklas Dimitrov", detailedPosition: .striker, age: 29, rating: 62),
            HistoricalPlayer(name: "Hugo Diallo", detailedPosition: .striker, age: 24, rating: 62, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Tariq Rousseau", detailedPosition: .striker, age: 20, rating: 50),
        ],
        "Solent": [
            HistoricalPlayer(name: "Emeka Salgueiro", detailedPosition: .goalkeeper, age: 33, rating: 70),
            HistoricalPlayer(name: "Lars Sandham", detailedPosition: .goalkeeper, age: 25, rating: 56),
            HistoricalPlayer(name: "Diego Ashworth", detailedPosition: .rightBack, age: 29, rating: 64),
            HistoricalPlayer(name: "Ivan Winters", detailedPosition: .centreBack, age: 25, rating: 72),
            HistoricalPlayer(name: "Noah Fontaine", detailedPosition: .centreBack, age: 27, rating: 64),
            HistoricalPlayer(name: "Rasmus Boateng", detailedPosition: .leftBack, age: 19, rating: 70, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Bruno Girard", detailedPosition: .leftBack, age: 31, rating: 58),
            HistoricalPlayer(name: "Kevin Zeman", detailedPosition: .centreBack, age: 31, rating: 62, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Anton Mensah", detailedPosition: .attackingMid, age: 31, rating: 80, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Lucas Harding", detailedPosition: .centralMid, age: 22, rating: 66),
            HistoricalPlayer(name: "Gordon Calder", detailedPosition: .holding, age: 31, rating: 64, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Anton Sandham", detailedPosition: .centralMid, age: 29, rating: 64),
            HistoricalPlayer(name: "Rasmus Camara", detailedPosition: .attackingMid, age: 27, rating: 66, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Kian Berg", detailedPosition: .rightWing, age: 25, rating: 58),
            HistoricalPlayer(name: "Anders Havel", detailedPosition: .striker, age: 22, rating: 68),
            HistoricalPlayer(name: "Craig Foulkes", detailedPosition: .striker, age: 23, rating: 72, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ryan Lefevre", detailedPosition: .striker, age: 23, rating: 64),
            HistoricalPlayer(name: "Daniel Adeyemi", detailedPosition: .striker, age: 31, rating: 60),
        ],
        "Tyneside": [
            HistoricalPlayer(name: "Shane Foulkes", detailedPosition: .goalkeeper, age: 24, rating: 82),
            HistoricalPlayer(name: "Noah Moreau", detailedPosition: .goalkeeper, age: 25, rating: 58),
            HistoricalPlayer(name: "Hassan Castellan", detailedPosition: .rightBack, age: 31, rating: 70),
            HistoricalPlayer(name: "Stefano Girard", detailedPosition: .centreBack, age: 21, rating: 68, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Mathis Grantham", detailedPosition: .leftBack, age: 20, rating: 64, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Marco Zeman", detailedPosition: .centreBack, age: 26, rating: 68),
            HistoricalPlayer(name: "Gustavo Toure", detailedPosition: .rightBack, age: 21, rating: 60),
            HistoricalPlayer(name: "Hector Dvorak", detailedPosition: .leftBack, age: 25, rating: 58, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Luca Larsen", detailedPosition: .centralMid, age: 30, rating: 80, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Emil Novak", detailedPosition: .leftWing, age: 21, rating: 79, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Gustavo Hartmann", detailedPosition: .rightWing, age: 25, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Tunde Hartmann", detailedPosition: .centralMid, age: 34, rating: 72, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Paul Calloway", detailedPosition: .holding, age: 26, rating: 62),
            HistoricalPlayer(name: "Youssef Krause", detailedPosition: .centralMid, age: 25, rating: 60),
            HistoricalPlayer(name: "Alan Truscott", detailedPosition: .striker, age: 29, rating: 91),
            HistoricalPlayer(name: "Rafael Havel", detailedPosition: .striker, age: 22, rating: 66),
            HistoricalPlayer(name: "Gareth Novak", detailedPosition: .striker, age: 33, rating: 60, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Mark Halvorsen", detailedPosition: .striker, age: 18, rating: 52),
        ],
        "White Hart Athletic": [
            HistoricalPlayer(name: "Bjorn Eriksson", detailedPosition: .goalkeeper, age: 28, rating: 74),
            HistoricalPlayer(name: "Stefano Latham", detailedPosition: .goalkeeper, age: 30, rating: 62),
            HistoricalPlayer(name: "Solomon Camwell", detailedPosition: .centreBack, age: 25, rating: 86),
            HistoricalPlayer(name: "Karim Boateng", detailedPosition: .rightBack, age: 23, rating: 72),
            HistoricalPlayer(name: "Emeka Radley", detailedPosition: .centreBack, age: 27, rating: 64),
            HistoricalPlayer(name: "Steven Aldous", detailedPosition: .leftBack, age: 30, rating: 64),
            HistoricalPlayer(name: "Diego Winters", detailedPosition: .centreBack, age: 20, rating: 58, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Emilio Sarr", detailedPosition: .centreBack, age: 19, rating: 64),
            HistoricalPlayer(name: "Daniel Baumann", detailedPosition: .centralMid, age: 34, rating: 72, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Wesley Fontaine", detailedPosition: .rightWing, age: 28, rating: 78, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Ryan Mensah", detailedPosition: .holding, age: 30, rating: 68),
            HistoricalPlayer(name: "Julio Sandham", detailedPosition: .centralMid, age: 29, rating: 68, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Marcus Serrano", detailedPosition: .rightWing, age: 24, rating: 58, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Petr Horvat", detailedPosition: .holding, age: 20, rating: 54, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Gustavo Ivanov", detailedPosition: .striker, age: 33, rating: 76),
            HistoricalPlayer(name: "Malick Fenwick", detailedPosition: .striker, age: 26, rating: 72, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Dean Kral", detailedPosition: .striker, age: 23, rating: 68),
            HistoricalPlayer(name: "Kofi Steiner", detailedPosition: .striker, age: 29, rating: 62),
        ],
        "Filbert Foxes": [
            HistoricalPlayer(name: "Petr Dimitrov", detailedPosition: .goalkeeper, age: 33, rating: 74),
            HistoricalPlayer(name: "Aaron Sandham", detailedPosition: .goalkeeper, age: 26, rating: 56),
            HistoricalPlayer(name: "Yusuf Ashcroft", detailedPosition: .centreBack, age: 31, rating: 74),
            HistoricalPlayer(name: "Luca Lefevre", detailedPosition: .centreBack, age: 29, rating: 66),
            HistoricalPlayer(name: "Freddy Whitfield", detailedPosition: .rightBack, age: 28, rating: 64, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Hugo Salgueiro", detailedPosition: .centreBack, age: 26, rating: 62, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Steven Moreau", detailedPosition: .leftBack, age: 24, rating: 64),
            HistoricalPlayer(name: "Scott Radley", detailedPosition: .leftBack, age: 18, rating: 50),
            HistoricalPlayer(name: "Craig Solheim", detailedPosition: .centralMid, age: 25, rating: 72, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Marcus Zeman", detailedPosition: .centralMid, age: 25, rating: 72, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Shane Rousseau", detailedPosition: .leftWing, age: 31, rating: 64),
            HistoricalPlayer(name: "Enzo Calder", detailedPosition: .rightWing, age: 28, rating: 62, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Felix Winstanley", detailedPosition: .rightWing, age: 25, rating: 56, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Mateo Girard", detailedPosition: .rightWing, age: 18, rating: 52),
            HistoricalPlayer(name: "Nathan Dvorak", detailedPosition: .striker, age: 25, rating: 70),
            HistoricalPlayer(name: "Scott Vasconcelos", detailedPosition: .striker, age: 27, rating: 64, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Pietro Keita", detailedPosition: .striker, age: 26, rating: 62),
            HistoricalPlayer(name: "Dario Mendes", detailedPosition: .striker, age: 27, rating: 56),
        ],
        "Teesside": [
            HistoricalPlayer(name: "Lucas Fenwick", detailedPosition: .goalkeeper, age: 27, rating: 80),
            HistoricalPlayer(name: "Gustavo Dvorak", detailedPosition: .goalkeeper, age: 31, rating: 58),
            HistoricalPlayer(name: "Scott Sherrington", detailedPosition: .centreBack, age: 35, rating: 74),
            HistoricalPlayer(name: "Emeka Prewitt", detailedPosition: .centreBack, age: 31, rating: 68, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Adam Sandham", detailedPosition: .rightBack, age: 31, rating: 62),
            HistoricalPlayer(name: "Callum Ashcroft", detailedPosition: .centreBack, age: 33, rating: 60, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Ethan Girard", detailedPosition: .centreBack, age: 32, rating: 58),
            HistoricalPlayer(name: "Mateo Lindqvist", detailedPosition: .leftBack, age: 27, rating: 56),
            HistoricalPlayer(name: "Henrik Vogel", detailedPosition: .centralMid, age: 32, rating: 78, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Ethan Sandham", detailedPosition: .centralMid, age: 29, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Stefano Blackwood", detailedPosition: .centralMid, age: 31, rating: 64, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Mathis Redfern", detailedPosition: .holding, age: 28, rating: 64, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Steven Petrov", detailedPosition: .rightWing, age: 27, rating: 58),
            HistoricalPlayer(name: "Marcus Dubois", detailedPosition: .rightWing, age: 30, rating: 56, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Tariq Steiner", detailedPosition: .striker, age: 30, rating: 78),
            HistoricalPlayer(name: "Wesley Duarte", detailedPosition: .striker, age: 25, rating: 68),
            HistoricalPlayer(name: "Chidi Devereux", detailedPosition: .striker, age: 32, rating: 66),
            HistoricalPlayer(name: "Marco Petrov", detailedPosition: .striker, age: 22, rating: 62, secondaryPositions: [.leftWing]),
        ],
        "Upton Athletic": [
            HistoricalPlayer(name: "Pietro Winstanley", detailedPosition: .goalkeeper, age: 31, rating: 74),
            HistoricalPlayer(name: "Hugo Ashworth", detailedPosition: .goalkeeper, age: 32, rating: 58),
            HistoricalPlayer(name: "Rio Ashworth", detailedPosition: .centreBack, age: 21, rating: 84, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Tariq Aldous", detailedPosition: .centreBack, age: 26, rating: 70, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Felipe Fontaine", detailedPosition: .centreBack, age: 32, rating: 66),
            HistoricalPlayer(name: "Tomas Foulkes", detailedPosition: .leftBack, age: 36, rating: 70),
            HistoricalPlayer(name: "Mateo Ndiaye", detailedPosition: .leftBack, age: 38, rating: 72, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Klaus Camara", detailedPosition: .centreBack, age: 26, rating: 58, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Frank Osgood", detailedPosition: .centralMid, age: 22, rating: 82, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Henrik Ivanov", detailedPosition: .rightWing, age: 26, rating: 76, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Kian Calder", detailedPosition: .attackingMid, age: 18, rating: 72, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Steven Marsh", detailedPosition: .centralMid, age: 26, rating: 66, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Yusuf Sarr", detailedPosition: .centralMid, age: 19, rating: 66, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Kian Lefevre", detailedPosition: .centralMid, age: 33, rating: 56),
            HistoricalPlayer(name: "Henrik Solheim", detailedPosition: .striker, age: 32, rating: 84, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Carlos Hartmann", detailedPosition: .striker, age: 22, rating: 74, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Erik Devereux", detailedPosition: .striker, age: 32, rating: 72),
            HistoricalPlayer(name: "Magnus Blackwood", detailedPosition: .striker, age: 17, rating: 58),
        ],
        "Goodison Blues": [
            HistoricalPlayer(name: "Kevin Duarte", detailedPosition: .goalkeeper, age: 27, rating: 68),
            HistoricalPlayer(name: "Gordon Nystrom", detailedPosition: .goalkeeper, age: 26, rating: 62),
            HistoricalPlayer(name: "Ivan Adeyemi", detailedPosition: .centreBack, age: 30, rating: 72, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Anton Horvat", detailedPosition: .leftBack, age: 26, rating: 68, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Stefano Keita", detailedPosition: .rightBack, age: 25, rating: 64, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Dean Sarr", detailedPosition: .leftBack, age: 26, rating: 64),
            HistoricalPlayer(name: "Shane Radley", detailedPosition: .leftBack, age: 20, rating: 64),
            HistoricalPlayer(name: "Wesley Havel", detailedPosition: .centreBack, age: 35, rating: 56),
            HistoricalPlayer(name: "Paul Winstanley", detailedPosition: .attackingMid, age: 33, rating: 78, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Connor Horvat", detailedPosition: .centralMid, age: 29, rating: 66, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Scott Ashcroft", detailedPosition: .rightWing, age: 28, rating: 66, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Dean Dubois", detailedPosition: .holding, age: 26, rating: 64, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Hector Vasconcelos", detailedPosition: .centralMid, age: 24, rating: 66, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Felipe Petrov", detailedPosition: .centralMid, age: 29, rating: 58),
            HistoricalPlayer(name: "Rasmus Nystrom", detailedPosition: .striker, age: 30, rating: 74),
            HistoricalPlayer(name: "Kyle Rousseau", detailedPosition: .striker, age: 28, rating: 74),
            HistoricalPlayer(name: "Neil Calder", detailedPosition: .striker, age: 19, rating: 66),
            HistoricalPlayer(name: "Ryan Halvorsen", detailedPosition: .striker, age: 29, rating: 58, secondaryPositions: [.rightWing]),
        ],
        "Pride Rams": [
            HistoricalPlayer(name: "Anton Kral", detailedPosition: .goalkeeper, age: 28, rating: 76),
            HistoricalPlayer(name: "Nathan Rusev", detailedPosition: .goalkeeper, age: 28, rating: 56),
            HistoricalPlayer(name: "Luca Halvorsen", detailedPosition: .centreBack, age: 31, rating: 64),
            HistoricalPlayer(name: "Petr Prentice", detailedPosition: .centreBack, age: 21, rating: 62, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Scott Diallo", detailedPosition: .centreBack, age: 28, rating: 56),
            HistoricalPlayer(name: "Andre Karlsen", detailedPosition: .centreBack, age: 20, rating: 56, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Scott Ivanov", detailedPosition: .rightBack, age: 23, rating: 54),
            HistoricalPlayer(name: "Niklas Novak", detailedPosition: .centreBack, age: 21, rating: 54),
            HistoricalPlayer(name: "Felipe Horvat", detailedPosition: .centralMid, age: 28, rating: 72, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Diego Vasconcelos", detailedPosition: .attackingMid, age: 27, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Viktor Vogel", detailedPosition: .centralMid, age: 24, rating: 64, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Enzo Vasconcelos", detailedPosition: .centralMid, age: 24, rating: 62, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Milan Salgueiro", detailedPosition: .centralMid, age: 21, rating: 64, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Lars Dimitrov", detailedPosition: .rightWing, age: 31, rating: 58, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Petr Fontaine", detailedPosition: .striker, age: 23, rating: 62),
            HistoricalPlayer(name: "Ethan Radley", detailedPosition: .striker, age: 20, rating: 62),
            HistoricalPlayer(name: "Shane Osgood", detailedPosition: .striker, age: 30, rating: 58),
            HistoricalPlayer(name: "Lars Mendes", detailedPosition: .striker, age: 20, rating: 48),
        ],
        "Etihad Blues": [
            HistoricalPlayer(name: "Ian Bernard", detailedPosition: .goalkeeper, age: 21, rating: 68),
            HistoricalPlayer(name: "Hugo Eriksson", detailedPosition: .goalkeeper, age: 26, rating: 56),
            HistoricalPlayer(name: "Yusuf Toure", detailedPosition: .centreBack, age: 29, rating: 66),
            HistoricalPlayer(name: "Magnus Dimitrov", detailedPosition: .rightBack, age: 25, rating: 62),
            HistoricalPlayer(name: "Marco Foulkes", detailedPosition: .centreBack, age: 28, rating: 60),
            HistoricalPlayer(name: "Sven Vasconcelos", detailedPosition: .rightBack, age: 27, rating: 62, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Rafael Novak", detailedPosition: .centreBack, age: 28, rating: 64, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Lucas Eriksson", detailedPosition: .centreBack, age: 24, rating: 56, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Pietro Marsh", detailedPosition: .rightWing, age: 31, rating: 72, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Emilio Baumann", detailedPosition: .centralMid, age: 27, rating: 64, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Bruno Blackwood", detailedPosition: .holding, age: 27, rating: 60, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Andre Osgood", detailedPosition: .centralMid, age: 27, rating: 56, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Diego Steiner", detailedPosition: .centralMid, age: 21, rating: 56, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Hassan Eriksson", detailedPosition: .leftWing, age: 24, rating: 58),
            HistoricalPlayer(name: "Emilio Osgood", detailedPosition: .striker, age: 30, rating: 68),
            HistoricalPlayer(name: "Andre Horvat", detailedPosition: .striker, age: 27, rating: 64),
            HistoricalPlayer(name: "Callum Blackwood", detailedPosition: .striker, age: 24, rating: 68, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Anton Aldous", detailedPosition: .striker, age: 24, rating: 66, secondaryPositions: [.rightWing]),
        ],
        "Highfield Athletic": [
            HistoricalPlayer(name: "Oskar Rusev", detailedPosition: .goalkeeper, age: 26, rating: 74),
            HistoricalPlayer(name: "Kyle Petrov", detailedPosition: .goalkeeper, age: 19, rating: 60),
            HistoricalPlayer(name: "Scott Winstanley", detailedPosition: .centreBack, age: 26, rating: 62),
            HistoricalPlayer(name: "Gustavo Whitfield", detailedPosition: .centreBack, age: 28, rating: 68),
            HistoricalPlayer(name: "Anders Serrano", detailedPosition: .rightBack, age: 29, rating: 60, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Rafael Dvorak", detailedPosition: .rightBack, age: 28, rating: 62),
            HistoricalPlayer(name: "Shane Latham", detailedPosition: .leftBack, age: 27, rating: 56),
            HistoricalPlayer(name: "Owen Horvat", detailedPosition: .centreBack, age: 30, rating: 56),
            HistoricalPlayer(name: "Luca Winstanley", detailedPosition: .attackingMid, age: 28, rating: 74, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Noah Larsen", detailedPosition: .holding, age: 25, rating: 64, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Freddy Solheim", detailedPosition: .rightWing, age: 24, rating: 62, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Hugo Redfern", detailedPosition: .leftWing, age: 24, rating: 58, secondaryPositions: [.leftBack]),
            HistoricalPlayer(name: "Ethan Bernard", detailedPosition: .holding, age: 29, rating: 64, secondaryPositions: [.centralMid]),
            HistoricalPlayer(name: "Bjorn Lindqvist", detailedPosition: .centralMid, age: 34, rating: 56, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Idris Latham", detailedPosition: .striker, age: 25, rating: 74),
            HistoricalPlayer(name: "Yusuf Winters", detailedPosition: .striker, age: 21, rating: 72, secondaryPositions: [.leftWing]),
            HistoricalPlayer(name: "Paul Hartmann", detailedPosition: .striker, age: 23, rating: 62),
            HistoricalPlayer(name: "Petr Harding", detailedPosition: .striker, age: 26, rating: 54),
        ],
        "Valley Parade": [
            HistoricalPlayer(name: "Lars Bernard", detailedPosition: .goalkeeper, age: 37, rating: 62),
            HistoricalPlayer(name: "Idris Winters", detailedPosition: .goalkeeper, age: 32, rating: 56),
            HistoricalPlayer(name: "Kevin Moreau", detailedPosition: .centreBack, age: 29, rating: 66),
            HistoricalPlayer(name: "Paul Latham", detailedPosition: .centreBack, age: 31, rating: 60),
            HistoricalPlayer(name: "Kyle Novak", detailedPosition: .rightBack, age: 34, rating: 60, secondaryPositions: [.centreBack]),
            HistoricalPlayer(name: "Emil Zeman", detailedPosition: .leftBack, age: 27, rating: 58),
            HistoricalPlayer(name: "Oskar Latham", detailedPosition: .rightBack, age: 25, rating: 54, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Danny Mensah", detailedPosition: .centreBack, age: 30, rating: 54, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Tunde Serrano", detailedPosition: .centralMid, age: 36, rating: 64, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Bruno Calder", detailedPosition: .leftWing, age: 34, rating: 64),
            HistoricalPlayer(name: "Emilio Mensah", detailedPosition: .leftWing, age: 29, rating: 62, secondaryPositions: [.striker]),
            HistoricalPlayer(name: "Kyle Moreau", detailedPosition: .centralMid, age: 27, rating: 56, secondaryPositions: [.holding]),
            HistoricalPlayer(name: "Henrik Whitfield", detailedPosition: .rightWing, age: 29, rating: 56, secondaryPositions: [.rightBack]),
            HistoricalPlayer(name: "Liam Keita", detailedPosition: .centralMid, age: 31, rating: 54),
            HistoricalPlayer(name: "Mateo Wenzel", detailedPosition: .striker, age: 28, rating: 70, secondaryPositions: [.attackingMid]),
            HistoricalPlayer(name: "Luca Moreau", detailedPosition: .striker, age: 29, rating: 60),
            HistoricalPlayer(name: "Idris Foulkes", detailedPosition: .striker, age: 24, rating: 58, secondaryPositions: [.rightWing]),
            HistoricalPlayer(name: "Felix Ashworth", detailedPosition: .striker, age: 38, rating: 56),
        ],
    ]
}
